// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsPrinterConnect(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashPrinterConnect(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsPrinterConnect(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsPrinterConnect(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsPrinterConnect(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsPrinterConnect(lhsKey, rhsKey) {
          if deepEqualsPrinterConnect(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsPrinterConnect(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashPrinterConnect(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashPrinterConnect(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashPrinterConnect(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashPrinterConnect(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashPrinterConnect(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashPrinterConnect(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum BleLogLevel: Int {
  case none = 0
  case error = 1
  case warning = 2
  case info = 3
  case debug = 4
  case verbose = 5
}

enum AvailabilityState: Int {
  case unknown = 0
  case resetting = 1
  case unsupported = 2
  case unauthorized = 3
  case poweredOff = 4
  case poweredOn = 5
}

enum BleConnectionState: Int {
  case connected = 0
  case disconnected = 1
  case connecting = 2
  case disconnecting = 3
}

enum BleInputProperty: Int {
  case disabled = 0
  case notification = 1
  case indication = 2
}

enum BleOutputProperty: Int {
  case withResponse = 0
  case withoutResponse = 1
}

enum BleConnectionPriority: Int {
  case balanced = 0
  case highPerformance = 1
  case lowPower = 2
}

enum AndroidScanMode: Int {
  case balanced = 0
  case lowLatency = 1
  case lowPower = 2
  case opportunistic = 3
}

enum AndroidScanCallbackType: Int {
  case allMatches = 0
  case firstMatch = 1
  case matchLost = 2
  case allMatchesAutoBatch = 3
}

enum AndroidScanMatchMode: Int {
  case aggressive = 0
  case sticky = 1
}

enum AndroidScanNumOfMatches: Int {
  case one = 0
  case few = 1
  case max = 2
}

enum CharacteristicProperty: Int {
  case broadcast = 0
  case read = 1
  case writeWithoutResponse = 2
  case write = 3
  case notify = 4
  case indicate = 5
  case authenticatedSignedWrites = 6
  case extendedProperties = 7
}

/// Generated class from Pigeon that represents data sent in messages.
struct UniversalBleScanResult: Hashable {
  var deviceId: String
  var name: String? = nil
  var rssi: Int64? = nil
  var manufacturerDataList: [UniversalManufacturerData]? = nil
  var serviceData: [String: FlutterStandardTypedData]? = nil
  var services: [String]? = nil
  var timestamp: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UniversalBleScanResult? {
    let deviceId = pigeonVar_list[0] as! String
    let name: String? = nilOrValue(pigeonVar_list[1])
    let rssi: Int64? = nilOrValue(pigeonVar_list[2])
    let manufacturerDataList: [UniversalManufacturerData]? = nilOrValue(pigeonVar_list[3])
    let serviceData: [String: FlutterStandardTypedData]? = nilOrValue(pigeonVar_list[4])
    let services: [String]? = nilOrValue(pigeonVar_list[5])
    let timestamp: Int64? = nilOrValue(pigeonVar_list[6])

    return UniversalBleScanResult(
      deviceId: deviceId,
      name: name,
      rssi: rssi,
      manufacturerDataList: manufacturerDataList,
      serviceData: serviceData,
      services: services,
      timestamp: timestamp
    )
  }
  func toList() -> [Any?] {
    return [
      deviceId,
      name,
      rssi,
      manufacturerDataList,
      serviceData,
      services,
      timestamp,
    ]
  }
  static func == (lhs: UniversalBleScanResult, rhs: UniversalBleScanResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.deviceId, rhs.deviceId) && deepEqualsPrinterConnect(lhs.name, rhs.name) && deepEqualsPrinterConnect(lhs.rssi, rhs.rssi) && deepEqualsPrinterConnect(lhs.manufacturerDataList, rhs.manufacturerDataList) && deepEqualsPrinterConnect(lhs.serviceData, rhs.serviceData) && deepEqualsPrinterConnect(lhs.services, rhs.services) && deepEqualsPrinterConnect(lhs.timestamp, rhs.timestamp)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UniversalBleScanResult")
    deepHashPrinterConnect(value: deviceId, hasher: &hasher)
    deepHashPrinterConnect(value: name, hasher: &hasher)
    deepHashPrinterConnect(value: rssi, hasher: &hasher)
    deepHashPrinterConnect(value: manufacturerDataList, hasher: &hasher)
    deepHashPrinterConnect(value: serviceData, hasher: &hasher)
    deepHashPrinterConnect(value: services, hasher: &hasher)
    deepHashPrinterConnect(value: timestamp, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UniversalBleService: Hashable {
  var uuid: String
  var characteristics: [UniversalBleCharacteristic]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UniversalBleService? {
    let uuid = pigeonVar_list[0] as! String
    let characteristics: [UniversalBleCharacteristic]? = nilOrValue(pigeonVar_list[1])

    return UniversalBleService(
      uuid: uuid,
      characteristics: characteristics
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      characteristics,
    ]
  }
  static func == (lhs: UniversalBleService, rhs: UniversalBleService) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.uuid, rhs.uuid) && deepEqualsPrinterConnect(lhs.characteristics, rhs.characteristics)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UniversalBleService")
    deepHashPrinterConnect(value: uuid, hasher: &hasher)
    deepHashPrinterConnect(value: characteristics, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UniversalBleCharacteristic: Hashable {
  var uuid: String
  var properties: [CharacteristicProperty]
  var descriptors: [UniversalBleDescriptor]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UniversalBleCharacteristic? {
    let uuid = pigeonVar_list[0] as! String
    let properties = pigeonVar_list[1] as! [CharacteristicProperty]
    let descriptors = pigeonVar_list[2] as! [UniversalBleDescriptor]

    return UniversalBleCharacteristic(
      uuid: uuid,
      properties: properties,
      descriptors: descriptors
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      properties,
      descriptors,
    ]
  }
  static func == (lhs: UniversalBleCharacteristic, rhs: UniversalBleCharacteristic) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.uuid, rhs.uuid) && deepEqualsPrinterConnect(lhs.properties, rhs.properties) && deepEqualsPrinterConnect(lhs.descriptors, rhs.descriptors)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UniversalBleCharacteristic")
    deepHashPrinterConnect(value: uuid, hasher: &hasher)
    deepHashPrinterConnect(value: properties, hasher: &hasher)
    deepHashPrinterConnect(value: descriptors, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UniversalBleDescriptor: Hashable {
  var uuid: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UniversalBleDescriptor? {
    let uuid = pigeonVar_list[0] as! String

    return UniversalBleDescriptor(
      uuid: uuid
    )
  }
  func toList() -> [Any?] {
    return [
      uuid
    ]
  }
  static func == (lhs: UniversalBleDescriptor, rhs: UniversalBleDescriptor) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.uuid, rhs.uuid)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UniversalBleDescriptor")
    deepHashPrinterConnect(value: uuid, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BleConnectionParametersUpdated: Hashable {
  var deviceId: String
  var interval: Int64
  var latency: Int64
  var supervisionTimeout: Int64
  var status: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BleConnectionParametersUpdated? {
    let deviceId = pigeonVar_list[0] as! String
    let interval = pigeonVar_list[1] as! Int64
    let latency = pigeonVar_list[2] as! Int64
    let supervisionTimeout = pigeonVar_list[3] as! Int64
    let status = pigeonVar_list[4] as! Int64

    return BleConnectionParametersUpdated(
      deviceId: deviceId,
      interval: interval,
      latency: latency,
      supervisionTimeout: supervisionTimeout,
      status: status
    )
  }
  func toList() -> [Any?] {
    return [
      deviceId,
      interval,
      latency,
      supervisionTimeout,
      status,
    ]
  }
  static func == (lhs: BleConnectionParametersUpdated, rhs: BleConnectionParametersUpdated) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.deviceId, rhs.deviceId) && deepEqualsPrinterConnect(lhs.interval, rhs.interval) && deepEqualsPrinterConnect(lhs.latency, rhs.latency) && deepEqualsPrinterConnect(lhs.supervisionTimeout, rhs.supervisionTimeout) && deepEqualsPrinterConnect(lhs.status, rhs.status)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BleConnectionParametersUpdated")
    deepHashPrinterConnect(value: deviceId, hasher: &hasher)
    deepHashPrinterConnect(value: interval, hasher: &hasher)
    deepHashPrinterConnect(value: latency, hasher: &hasher)
    deepHashPrinterConnect(value: supervisionTimeout, hasher: &hasher)
    deepHashPrinterConnect(value: status, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AndroidOptions: Hashable {
  var requestLocationPermission: Bool? = nil
  var scanMode: AndroidScanMode? = nil
  var reportDelayMillis: Int64? = nil
  var callbackType: [AndroidScanCallbackType]? = nil
  var matchMode: AndroidScanMatchMode? = nil
  var numOfMatches: AndroidScanNumOfMatches? = nil
  var legacy: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AndroidOptions? {
    let requestLocationPermission: Bool? = nilOrValue(pigeonVar_list[0])
    let scanMode: AndroidScanMode? = nilOrValue(pigeonVar_list[1])
    let reportDelayMillis: Int64? = nilOrValue(pigeonVar_list[2])
    let callbackType: [AndroidScanCallbackType]? = nilOrValue(pigeonVar_list[3])
    let matchMode: AndroidScanMatchMode? = nilOrValue(pigeonVar_list[4])
    let numOfMatches: AndroidScanNumOfMatches? = nilOrValue(pigeonVar_list[5])
    let legacy: Bool? = nilOrValue(pigeonVar_list[6])

    return AndroidOptions(
      requestLocationPermission: requestLocationPermission,
      scanMode: scanMode,
      reportDelayMillis: reportDelayMillis,
      callbackType: callbackType,
      matchMode: matchMode,
      numOfMatches: numOfMatches,
      legacy: legacy
    )
  }
  func toList() -> [Any?] {
    return [
      requestLocationPermission,
      scanMode,
      reportDelayMillis,
      callbackType,
      matchMode,
      numOfMatches,
      legacy,
    ]
  }
  static func == (lhs: AndroidOptions, rhs: AndroidOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.requestLocationPermission, rhs.requestLocationPermission) && deepEqualsPrinterConnect(lhs.scanMode, rhs.scanMode) && deepEqualsPrinterConnect(lhs.reportDelayMillis, rhs.reportDelayMillis) && deepEqualsPrinterConnect(lhs.callbackType, rhs.callbackType) && deepEqualsPrinterConnect(lhs.matchMode, rhs.matchMode) && deepEqualsPrinterConnect(lhs.numOfMatches, rhs.numOfMatches) && deepEqualsPrinterConnect(lhs.legacy, rhs.legacy)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AndroidOptions")
    deepHashPrinterConnect(value: requestLocationPermission, hasher: &hasher)
    deepHashPrinterConnect(value: scanMode, hasher: &hasher)
    deepHashPrinterConnect(value: reportDelayMillis, hasher: &hasher)
    deepHashPrinterConnect(value: callbackType, hasher: &hasher)
    deepHashPrinterConnect(value: matchMode, hasher: &hasher)
    deepHashPrinterConnect(value: numOfMatches, hasher: &hasher)
    deepHashPrinterConnect(value: legacy, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UniversalScanConfig: Hashable {
  var android: AndroidOptions? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UniversalScanConfig? {
    let android: AndroidOptions? = nilOrValue(pigeonVar_list[0])

    return UniversalScanConfig(
      android: android
    )
  }
  func toList() -> [Any?] {
    return [
      android
    ]
  }
  static func == (lhs: UniversalScanConfig, rhs: UniversalScanConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.android, rhs.android)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UniversalScanConfig")
    deepHashPrinterConnect(value: android, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UniversalScanFilter: Hashable {
  var withServices: [String]
  var withNamePrefix: [String]
  var withManufacturerData: [ManufacturerDataFilter]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UniversalScanFilter? {
    let withServices = pigeonVar_list[0] as! [String]
    let withNamePrefix = pigeonVar_list[1] as! [String]
    let withManufacturerData = pigeonVar_list[2] as! [ManufacturerDataFilter]

    return UniversalScanFilter(
      withServices: withServices,
      withNamePrefix: withNamePrefix,
      withManufacturerData: withManufacturerData
    )
  }
  func toList() -> [Any?] {
    return [
      withServices,
      withNamePrefix,
      withManufacturerData,
    ]
  }
  static func == (lhs: UniversalScanFilter, rhs: UniversalScanFilter) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.withServices, rhs.withServices) && deepEqualsPrinterConnect(lhs.withNamePrefix, rhs.withNamePrefix) && deepEqualsPrinterConnect(lhs.withManufacturerData, rhs.withManufacturerData)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UniversalScanFilter")
    deepHashPrinterConnect(value: withServices, hasher: &hasher)
    deepHashPrinterConnect(value: withNamePrefix, hasher: &hasher)
    deepHashPrinterConnect(value: withManufacturerData, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ManufacturerDataFilter: Hashable {
  var companyIdentifier: Int64
  var payloadPrefix: FlutterStandardTypedData? = nil
  var payloadMask: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ManufacturerDataFilter? {
    let companyIdentifier = pigeonVar_list[0] as! Int64
    let payloadPrefix: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[1])
    let payloadMask: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[2])

    return ManufacturerDataFilter(
      companyIdentifier: companyIdentifier,
      payloadPrefix: payloadPrefix,
      payloadMask: payloadMask
    )
  }
  func toList() -> [Any?] {
    return [
      companyIdentifier,
      payloadPrefix,
      payloadMask,
    ]
  }
  static func == (lhs: ManufacturerDataFilter, rhs: ManufacturerDataFilter) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.companyIdentifier, rhs.companyIdentifier) && deepEqualsPrinterConnect(lhs.payloadPrefix, rhs.payloadPrefix) && deepEqualsPrinterConnect(lhs.payloadMask, rhs.payloadMask)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ManufacturerDataFilter")
    deepHashPrinterConnect(value: companyIdentifier, hasher: &hasher)
    deepHashPrinterConnect(value: payloadPrefix, hasher: &hasher)
    deepHashPrinterConnect(value: payloadMask, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UniversalManufacturerData: Hashable {
  var companyIdentifier: Int64
  var data: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UniversalManufacturerData? {
    let companyIdentifier = pigeonVar_list[0] as! Int64
    let data = pigeonVar_list[1] as! FlutterStandardTypedData

    return UniversalManufacturerData(
      companyIdentifier: companyIdentifier,
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      companyIdentifier,
      data,
    ]
  }
  static func == (lhs: UniversalManufacturerData, rhs: UniversalManufacturerData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.companyIdentifier, rhs.companyIdentifier) && deepEqualsPrinterConnect(lhs.data, rhs.data)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UniversalManufacturerData")
    deepHashPrinterConnect(value: companyIdentifier, hasher: &hasher)
    deepHashPrinterConnect(value: data, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AppleConnectionOptions: Hashable {
  var notifyOnConnection: Bool? = nil
  var notifyOnDisconnection: Bool? = nil
  var notifyOnNotification: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AppleConnectionOptions? {
    let notifyOnConnection: Bool? = nilOrValue(pigeonVar_list[0])
    let notifyOnDisconnection: Bool? = nilOrValue(pigeonVar_list[1])
    let notifyOnNotification: Bool? = nilOrValue(pigeonVar_list[2])

    return AppleConnectionOptions(
      notifyOnConnection: notifyOnConnection,
      notifyOnDisconnection: notifyOnDisconnection,
      notifyOnNotification: notifyOnNotification
    )
  }
  func toList() -> [Any?] {
    return [
      notifyOnConnection,
      notifyOnDisconnection,
      notifyOnNotification,
    ]
  }
  static func == (lhs: AppleConnectionOptions, rhs: AppleConnectionOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.notifyOnConnection, rhs.notifyOnConnection) && deepEqualsPrinterConnect(lhs.notifyOnDisconnection, rhs.notifyOnDisconnection) && deepEqualsPrinterConnect(lhs.notifyOnNotification, rhs.notifyOnNotification)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AppleConnectionOptions")
    deepHashPrinterConnect(value: notifyOnConnection, hasher: &hasher)
    deepHashPrinterConnect(value: notifyOnDisconnection, hasher: &hasher)
    deepHashPrinterConnect(value: notifyOnNotification, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ConnectionPlatformConfig: Hashable {
  var apple: AppleConnectionOptions? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConnectionPlatformConfig? {
    let apple: AppleConnectionOptions? = nilOrValue(pigeonVar_list[0])

    return ConnectionPlatformConfig(
      apple: apple
    )
  }
  func toList() -> [Any?] {
    return [
      apple
    ]
  }
  static func == (lhs: ConnectionPlatformConfig, rhs: ConnectionPlatformConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.apple, rhs.apple)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConnectionPlatformConfig")
    deepHashPrinterConnect(value: apple, hasher: &hasher)
  }
}

private class PrinterConnectPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BleLogLevel(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AvailabilityState(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BleConnectionState(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BleInputProperty(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BleOutputProperty(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BleConnectionPriority(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AndroidScanMode(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AndroidScanCallbackType(rawValue: enumResultAsInt)
      }
      return nil
    case 137:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AndroidScanMatchMode(rawValue: enumResultAsInt)
      }
      return nil
    case 138:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AndroidScanNumOfMatches(rawValue: enumResultAsInt)
      }
      return nil
    case 139:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CharacteristicProperty(rawValue: enumResultAsInt)
      }
      return nil
    case 140:
      return UniversalBleScanResult.fromList(self.readValue() as! [Any?])
    case 141:
      return UniversalBleService.fromList(self.readValue() as! [Any?])
    case 142:
      return UniversalBleCharacteristic.fromList(self.readValue() as! [Any?])
    case 143:
      return UniversalBleDescriptor.fromList(self.readValue() as! [Any?])
    case 144:
      return BleConnectionParametersUpdated.fromList(self.readValue() as! [Any?])
    case 145:
      return AndroidOptions.fromList(self.readValue() as! [Any?])
    case 146:
      return UniversalScanConfig.fromList(self.readValue() as! [Any?])
    case 147:
      return UniversalScanFilter.fromList(self.readValue() as! [Any?])
    case 148:
      return ManufacturerDataFilter.fromList(self.readValue() as! [Any?])
    case 149:
      return UniversalManufacturerData.fromList(self.readValue() as! [Any?])
    case 150:
      return AppleConnectionOptions.fromList(self.readValue() as! [Any?])
    case 151:
      return ConnectionPlatformConfig.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PrinterConnectPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BleLogLevel {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? AvailabilityState {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? BleConnectionState {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? BleInputProperty {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? BleOutputProperty {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? BleConnectionPriority {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? AndroidScanMode {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? AndroidScanCallbackType {
      super.writeByte(136)
      super.writeValue(value.rawValue)
    } else if let value = value as? AndroidScanMatchMode {
      super.writeByte(137)
      super.writeValue(value.rawValue)
    } else if let value = value as? AndroidScanNumOfMatches {
      super.writeByte(138)
      super.writeValue(value.rawValue)
    } else if let value = value as? CharacteristicProperty {
      super.writeByte(139)
      super.writeValue(value.rawValue)
    } else if let value = value as? UniversalBleScanResult {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? UniversalBleService {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? UniversalBleCharacteristic {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? UniversalBleDescriptor {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? BleConnectionParametersUpdated {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? AndroidOptions {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? UniversalScanConfig {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? UniversalScanFilter {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? ManufacturerDataFilter {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? UniversalManufacturerData {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? AppleConnectionOptions {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else if let value = value as? ConnectionPlatformConfig {
      super.writeByte(151)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PrinterConnectPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PrinterConnectPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PrinterConnectPigeonCodecWriter(data: data)
  }
}

class PrinterConnectPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PrinterConnectPigeonCodec(readerWriter: PrinterConnectPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol UniversalBlePlatformChannel {
  func getBluetoothAvailabilityState(completion: @escaping (Result<AvailabilityState, Error>) -> Void)
  func hasPermissions(withAndroidFineLocation: Bool) throws -> Bool
  func requestPermissions(withAndroidFineLocation: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  func enableBluetooth(completion: @escaping (Result<Bool, Error>) -> Void)
  func startScan(filter: UniversalScanFilter?, config: UniversalScanConfig?) throws
  func stopScan() throws
  func isScanning() throws -> Bool
  func connect(deviceId: String, autoConnect: Bool?, platformConfig: ConnectionPlatformConfig?) throws
  func disconnect(deviceId: String) throws
  func setNotifiable(deviceId: String, service: String, characteristic: String, bleInputProperty: BleInputProperty, completion: @escaping (Result<Void, Error>) -> Void)
  func discoverServices(deviceId: String, withDescriptors: Bool, completion: @escaping (Result<[UniversalBleService], Error>) -> Void)
  func readValue(deviceId: String, service: String, characteristic: String, completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
  func requestMtu(deviceId: String, expectedMtu: Int64, completion: @escaping (Result<Int64, Error>) -> Void)
  func writeValue(deviceId: String, service: String, characteristic: String, value: FlutterStandardTypedData, bleOutputProperty: BleOutputProperty, completion: @escaping (Result<Void, Error>) -> Void)
  func getSystemDevices(withServices: [String], completion: @escaping (Result<[UniversalBleScanResult], Error>) -> Void)
  func getConnectionState(deviceId: String) throws -> BleConnectionState
  func readRssi(deviceId: String, completion: @escaping (Result<Int64, Error>) -> Void)
  func requestConnectionPriority(deviceId: String, priority: BleConnectionPriority, completion: @escaping (Result<Void, Error>) -> Void)
  func setLogLevel(logLevel: BleLogLevel) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class UniversalBlePlatformChannelSetup {
  static var codec: FlutterStandardMessageCodec { PrinterConnectPigeonCodec.shared }
  /// Sets up an instance of `UniversalBlePlatformChannel` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: UniversalBlePlatformChannel?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getBluetoothAvailabilityStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.getBluetoothAvailabilityState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBluetoothAvailabilityStateChannel.setMessageHandler { _, reply in
        api.getBluetoothAvailabilityState { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getBluetoothAvailabilityStateChannel.setMessageHandler(nil)
    }
    let hasPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.hasPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hasPermissionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let withAndroidFineLocationArg = args[0] as! Bool
        do {
          let result = try api.hasPermissions(withAndroidFineLocation: withAndroidFineLocationArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      hasPermissionsChannel.setMessageHandler(nil)
    }
    let requestPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.requestPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let withAndroidFineLocationArg = args[0] as! Bool
        api.requestPermissions(withAndroidFineLocation: withAndroidFineLocationArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionsChannel.setMessageHandler(nil)
    }
    let enableBluetoothChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.enableBluetooth\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enableBluetoothChannel.setMessageHandler { _, reply in
        api.enableBluetooth { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      enableBluetoothChannel.setMessageHandler(nil)
    }
    let startScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.startScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startScanChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filterArg: UniversalScanFilter? = nilOrValue(args[0])
        let configArg: UniversalScanConfig? = nilOrValue(args[1])
        do {
          try api.startScan(filter: filterArg, config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startScanChannel.setMessageHandler(nil)
    }
    let stopScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.stopScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopScanChannel.setMessageHandler { _, reply in
        do {
          try api.stopScan()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopScanChannel.setMessageHandler(nil)
    }
    let isScanningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.isScanning\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isScanningChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isScanning()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isScanningChannel.setMessageHandler(nil)
    }
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.connect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let autoConnectArg: Bool? = nilOrValue(args[1])
        let platformConfigArg: ConnectionPlatformConfig? = nilOrValue(args[2])
        do {
          try api.connect(deviceId: deviceIdArg, autoConnect: autoConnectArg, platformConfig: platformConfigArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.disconnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        do {
          try api.disconnect(deviceId: deviceIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    let setNotifiableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.setNotifiable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setNotifiableChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let serviceArg = args[1] as! String
        let characteristicArg = args[2] as! String
        let bleInputPropertyArg = args[3] as! BleInputProperty
        api.setNotifiable(deviceId: deviceIdArg, service: serviceArg, characteristic: characteristicArg, bleInputProperty: bleInputPropertyArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setNotifiableChannel.setMessageHandler(nil)
    }
    let discoverServicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.discoverServices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      discoverServicesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let withDescriptorsArg = args[1] as! Bool
        api.discoverServices(deviceId: deviceIdArg, withDescriptors: withDescriptorsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      discoverServicesChannel.setMessageHandler(nil)
    }
    let readValueChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.readValue\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readValueChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let serviceArg = args[1] as! String
        let characteristicArg = args[2] as! String
        api.readValue(deviceId: deviceIdArg, service: serviceArg, characteristic: characteristicArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readValueChannel.setMessageHandler(nil)
    }
    let requestMtuChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.requestMtu\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestMtuChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let expectedMtuArg = args[1] as! Int64
        api.requestMtu(deviceId: deviceIdArg, expectedMtu: expectedMtuArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestMtuChannel.setMessageHandler(nil)
    }
    let writeValueChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.writeValue\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      writeValueChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let serviceArg = args[1] as! String
        let characteristicArg = args[2] as! String
        let valueArg = args[3] as! FlutterStandardTypedData
        let bleOutputPropertyArg = args[4] as! BleOutputProperty
        api.writeValue(deviceId: deviceIdArg, service: serviceArg, characteristic: characteristicArg, value: valueArg, bleOutputProperty: bleOutputPropertyArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      writeValueChannel.setMessageHandler(nil)
    }
    let getSystemDevicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.getSystemDevices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSystemDevicesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let withServicesArg = args[0] as! [String]
        api.getSystemDevices(withServices: withServicesArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getSystemDevicesChannel.setMessageHandler(nil)
    }
    let getConnectionStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.getConnectionState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getConnectionStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        do {
          let result = try api.getConnectionState(deviceId: deviceIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getConnectionStateChannel.setMessageHandler(nil)
    }
    let readRssiChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.readRssi\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readRssiChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        api.readRssi(deviceId: deviceIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readRssiChannel.setMessageHandler(nil)
    }
    let requestConnectionPriorityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.requestConnectionPriority\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestConnectionPriorityChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let priorityArg = args[1] as! BleConnectionPriority
        api.requestConnectionPriority(deviceId: deviceIdArg, priority: priorityArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestConnectionPriorityChannel.setMessageHandler(nil)
    }
    let setLogLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.setLogLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLogLevelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let logLevelArg = args[0] as! BleLogLevel
        do {
          try api.setLogLevel(logLevel: logLevelArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setLogLevelChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol UniversalBleCallbackChannelProtocol {
  func onAvailabilityChanged(state stateArg: AvailabilityState, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onScanResult(result resultArg: UniversalBleScanResult, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onValueChanged(deviceId deviceIdArg: String, characteristicId characteristicIdArg: String, value valueArg: FlutterStandardTypedData, timestamp timestampArg: Int64?, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onConnectionChanged(deviceId deviceIdArg: String, connected connectedArg: Bool, error errorArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onConnectionParametersUpdated(update updateArg: BleConnectionParametersUpdated, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class UniversalBleCallbackChannel: UniversalBleCallbackChannelProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PrinterConnectPigeonCodec {
    return PrinterConnectPigeonCodec.shared
  }
  func onAvailabilityChanged(state stateArg: AvailabilityState, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onAvailabilityChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onScanResult(result resultArg: UniversalBleScanResult, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onScanResult\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([resultArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onValueChanged(deviceId deviceIdArg: String, characteristicId characteristicIdArg: String, value valueArg: FlutterStandardTypedData, timestamp timestampArg: Int64?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onValueChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceIdArg, characteristicIdArg, valueArg, timestampArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onConnectionChanged(deviceId deviceIdArg: String, connected connectedArg: Bool, error errorArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onConnectionChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceIdArg, connectedArg, errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onConnectionParametersUpdated(update updateArg: BleConnectionParametersUpdated, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onConnectionParametersUpdated\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([updateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
