// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsPrinterConnect(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashPrinterConnect(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsPrinterConnect(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsPrinterConnect(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsPrinterConnect(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsPrinterConnect(lhsKey, rhsKey) {
          if deepEqualsPrinterConnect(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsPrinterConnect(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashPrinterConnect(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashPrinterConnect(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashPrinterConnect(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashPrinterConnect(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashPrinterConnect(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashPrinterConnect(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum BleLogLevel: Int {
  case verbose = 0
  case debug = 1
  case info = 2
  case warning = 3
  case error = 4
  case wtf = 5
  case none = 6
}

enum AvailabilityState: Int {
  case unknown = 0
  case resetting = 1
  case unsupported = 2
  case unauthorized = 3
  case poweredOff = 4
  case poweredOn = 5
}

enum BleConnectionState: Int {
  case disconnected = 0
  case connecting = 1
  case connected = 2
  case disconnecting = 3
}

enum BleInputProperty: Int {
  case disabled = 0
  case notification = 1
  case indication = 2
}

enum BleOutputProperty: Int {
  case none = 0
  case write = 1
  case writeWithoutResponse = 2
}

enum BleConnectionPriority: Int {
  case balanced = 0
  case highPerformance = 1
  case lowPower = 2
}

enum AndroidScanMode: Int {
  case lowPowered = 0
  case balanced = 1
  case lowLatency = 2
}

enum AndroidScanCallbackType: Int {
  case default = 0
  case firstMatch = 1
  case lose = 2
  case matched = 3
}

enum AndroidScanMatchMode: Int {
  case default = 0
  case sticky = 1
}

enum AndroidScanNumOfMatches: Int {
  case one = 0
  case few = 1
  case many = 2
}

enum CharacteristicProperty: Int {
  case read = 0
  case write = 1
  case writeWithoutResponse = 2
  case notify = 3
  case indicate = 4
  case broadcast = 5
  case extendedSbleProps = 6
  case signedWrite = 7
}

/// Generated class from Pigeon that represents data sent in messages.
struct UniversalBleScanResult: Hashable {
  var peripheralId: String
  var name: String? = nil
  var rssi: Int64
  var manufacturerData: [UniversalManufacturerData]? = nil
  var serviceData: [Int64]? = nil
  var serviceUuids: [String]? = nil
  var txPowerLevel: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UniversalBleScanResult? {
    let peripheralId = pigeonVar_list[0] as! String
    let name: String? = nilOrValue(pigeonVar_list[1])
    let rssi = pigeonVar_list[2] as! Int64
    let manufacturerData: [UniversalManufacturerData]? = nilOrValue(pigeonVar_list[3])
    let serviceData: [Int64]? = nilOrValue(pigeonVar_list[4])
    let serviceUuids: [String]? = nilOrValue(pigeonVar_list[5])
    let txPowerLevel: Int64? = nilOrValue(pigeonVar_list[6])

    return UniversalBleScanResult(
      peripheralId: peripheralId,
      name: name,
      rssi: rssi,
      manufacturerData: manufacturerData,
      serviceData: serviceData,
      serviceUuids: serviceUuids,
      txPowerLevel: txPowerLevel
    )
  }
  func toList() -> [Any?] {
    return [
      peripheralId,
      name,
      rssi,
      manufacturerData,
      serviceData,
      serviceUuids,
      txPowerLevel,
    ]
  }
  static func == (lhs: UniversalBleScanResult, rhs: UniversalBleScanResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.peripheralId, rhs.peripheralId) && deepEqualsPrinterConnect(lhs.name, rhs.name) && deepEqualsPrinterConnect(lhs.rssi, rhs.rssi) && deepEqualsPrinterConnect(lhs.manufacturerData, rhs.manufacturerData) && deepEqualsPrinterConnect(lhs.serviceData, rhs.serviceData) && deepEqualsPrinterConnect(lhs.serviceUuids, rhs.serviceUuids) && deepEqualsPrinterConnect(lhs.txPowerLevel, rhs.txPowerLevel)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UniversalBleScanResult")
    deepHashPrinterConnect(value: peripheralId, hasher: &hasher)
    deepHashPrinterConnect(value: name, hasher: &hasher)
    deepHashPrinterConnect(value: rssi, hasher: &hasher)
    deepHashPrinterConnect(value: manufacturerData, hasher: &hasher)
    deepHashPrinterConnect(value: serviceData, hasher: &hasher)
    deepHashPrinterConnect(value: serviceUuids, hasher: &hasher)
    deepHashPrinterConnect(value: txPowerLevel, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UniversalManufacturerData: Hashable {
  var id: Int64
  var data: [Int64]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UniversalManufacturerData? {
    let id = pigeonVar_list[0] as! Int64
    let data = pigeonVar_list[1] as! [Int64]

    return UniversalManufacturerData(
      id: id,
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      data,
    ]
  }
  static func == (lhs: UniversalManufacturerData, rhs: UniversalManufacturerData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.id, rhs.id) && deepEqualsPrinterConnect(lhs.data, rhs.data)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UniversalManufacturerData")
    deepHashPrinterConnect(value: id, hasher: &hasher)
    deepHashPrinterConnect(value: data, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UniversalBleService: Hashable {
  var uuid: String
  var isPrimary: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UniversalBleService? {
    let uuid = pigeonVar_list[0] as! String
    let isPrimary = pigeonVar_list[1] as! Bool

    return UniversalBleService(
      uuid: uuid,
      isPrimary: isPrimary
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      isPrimary,
    ]
  }
  static func == (lhs: UniversalBleService, rhs: UniversalBleService) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.uuid, rhs.uuid) && deepEqualsPrinterConnect(lhs.isPrimary, rhs.isPrimary)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UniversalBleService")
    deepHashPrinterConnect(value: uuid, hasher: &hasher)
    deepHashPrinterConnect(value: isPrimary, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UniversalBleCharacteristic: Hashable {
  var uuid: String
  var properties: [CharacteristicProperty]
  var value: [Int64]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UniversalBleCharacteristic? {
    let uuid = pigeonVar_list[0] as! String
    let properties = pigeonVar_list[1] as! [CharacteristicProperty]
    let value: [Int64]? = nilOrValue(pigeonVar_list[2])

    return UniversalBleCharacteristic(
      uuid: uuid,
      properties: properties,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      properties,
      value,
    ]
  }
  static func == (lhs: UniversalBleCharacteristic, rhs: UniversalBleCharacteristic) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.uuid, rhs.uuid) && deepEqualsPrinterConnect(lhs.properties, rhs.properties) && deepEqualsPrinterConnect(lhs.value, rhs.value)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UniversalBleCharacteristic")
    deepHashPrinterConnect(value: uuid, hasher: &hasher)
    deepHashPrinterConnect(value: properties, hasher: &hasher)
    deepHashPrinterConnect(value: value, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UniversalBleDescriptor: Hashable {
  var uuid: String
  var value: [Int64]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UniversalBleDescriptor? {
    let uuid = pigeonVar_list[0] as! String
    let value: [Int64]? = nilOrValue(pigeonVar_list[1])

    return UniversalBleDescriptor(
      uuid: uuid,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      value,
    ]
  }
  static func == (lhs: UniversalBleDescriptor, rhs: UniversalBleDescriptor) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.uuid, rhs.uuid) && deepEqualsPrinterConnect(lhs.value, rhs.value)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UniversalBleDescriptor")
    deepHashPrinterConnect(value: uuid, hasher: &hasher)
    deepHashPrinterConnect(value: value, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AndroidOptions: Hashable {
  var scanMode: AndroidScanMode? = nil
  var callbackType: AndroidScanCallbackType? = nil
  var matchMode: AndroidScanMatchMode? = nil
  var numOfMatches: AndroidScanNumOfMatches? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AndroidOptions? {
    let scanMode: AndroidScanMode? = nilOrValue(pigeonVar_list[0])
    let callbackType: AndroidScanCallbackType? = nilOrValue(pigeonVar_list[1])
    let matchMode: AndroidScanMatchMode? = nilOrValue(pigeonVar_list[2])
    let numOfMatches: AndroidScanNumOfMatches? = nilOrValue(pigeonVar_list[3])

    return AndroidOptions(
      scanMode: scanMode,
      callbackType: callbackType,
      matchMode: matchMode,
      numOfMatches: numOfMatches
    )
  }
  func toList() -> [Any?] {
    return [
      scanMode,
      callbackType,
      matchMode,
      numOfMatches,
    ]
  }
  static func == (lhs: AndroidOptions, rhs: AndroidOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.scanMode, rhs.scanMode) && deepEqualsPrinterConnect(lhs.callbackType, rhs.callbackType) && deepEqualsPrinterConnect(lhs.matchMode, rhs.matchMode) && deepEqualsPrinterConnect(lhs.numOfMatches, rhs.numOfMatches)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AndroidOptions")
    deepHashPrinterConnect(value: scanMode, hasher: &hasher)
    deepHashPrinterConnect(value: callbackType, hasher: &hasher)
    deepHashPrinterConnect(value: matchMode, hasher: &hasher)
    deepHashPrinterConnect(value: numOfMatches, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UniversalScanConfig: Hashable {
  var scanFilters: [UniversalScanFilter]? = nil
  var androidOptions: AndroidOptions? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UniversalScanConfig? {
    let scanFilters: [UniversalScanFilter]? = nilOrValue(pigeonVar_list[0])
    let androidOptions: AndroidOptions? = nilOrValue(pigeonVar_list[1])

    return UniversalScanConfig(
      scanFilters: scanFilters,
      androidOptions: androidOptions
    )
  }
  func toList() -> [Any?] {
    return [
      scanFilters,
      androidOptions,
    ]
  }
  static func == (lhs: UniversalScanConfig, rhs: UniversalScanConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.scanFilters, rhs.scanFilters) && deepEqualsPrinterConnect(lhs.androidOptions, rhs.androidOptions)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UniversalScanConfig")
    deepHashPrinterConnect(value: scanFilters, hasher: &hasher)
    deepHashPrinterConnect(value: androidOptions, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UniversalScanFilter: Hashable {
  var withServices: [String]? = nil
  var withManufacturerData: [ManufacturerDataFilter]? = nil
  var withLocalName: String? = nil
  var withLocalNamePrefix: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UniversalScanFilter? {
    let withServices: [String]? = nilOrValue(pigeonVar_list[0])
    let withManufacturerData: [ManufacturerDataFilter]? = nilOrValue(pigeonVar_list[1])
    let withLocalName: String? = nilOrValue(pigeonVar_list[2])
    let withLocalNamePrefix: String? = nilOrValue(pigeonVar_list[3])

    return UniversalScanFilter(
      withServices: withServices,
      withManufacturerData: withManufacturerData,
      withLocalName: withLocalName,
      withLocalNamePrefix: withLocalNamePrefix
    )
  }
  func toList() -> [Any?] {
    return [
      withServices,
      withManufacturerData,
      withLocalName,
      withLocalNamePrefix,
    ]
  }
  static func == (lhs: UniversalScanFilter, rhs: UniversalScanFilter) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.withServices, rhs.withServices) && deepEqualsPrinterConnect(lhs.withManufacturerData, rhs.withManufacturerData) && deepEqualsPrinterConnect(lhs.withLocalName, rhs.withLocalName) && deepEqualsPrinterConnect(lhs.withLocalNamePrefix, rhs.withLocalNamePrefix)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UniversalScanFilter")
    deepHashPrinterConnect(value: withServices, hasher: &hasher)
    deepHashPrinterConnect(value: withManufacturerData, hasher: &hasher)
    deepHashPrinterConnect(value: withLocalName, hasher: &hasher)
    deepHashPrinterConnect(value: withLocalNamePrefix, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ManufacturerDataFilter: Hashable {
  var companyId: Int64
  var data: [Int64]? = nil
  var mask: [Int64]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ManufacturerDataFilter? {
    let companyId = pigeonVar_list[0] as! Int64
    let data: [Int64]? = nilOrValue(pigeonVar_list[1])
    let mask: [Int64]? = nilOrValue(pigeonVar_list[2])

    return ManufacturerDataFilter(
      companyId: companyId,
      data: data,
      mask: mask
    )
  }
  func toList() -> [Any?] {
    return [
      companyId,
      data,
      mask,
    ]
  }
  static func == (lhs: ManufacturerDataFilter, rhs: ManufacturerDataFilter) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.companyId, rhs.companyId) && deepEqualsPrinterConnect(lhs.data, rhs.data) && deepEqualsPrinterConnect(lhs.mask, rhs.mask)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ManufacturerDataFilter")
    deepHashPrinterConnect(value: companyId, hasher: &hasher)
    deepHashPrinterConnect(value: data, hasher: &hasher)
    deepHashPrinterConnect(value: mask, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AppleConnectionOptions: Hashable {
  var shouldRestoreState: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AppleConnectionOptions? {
    let shouldRestoreState: Bool? = nilOrValue(pigeonVar_list[0])

    return AppleConnectionOptions(
      shouldRestoreState: shouldRestoreState
    )
  }
  func toList() -> [Any?] {
    return [
      shouldRestoreState
    ]
  }
  static func == (lhs: AppleConnectionOptions, rhs: AppleConnectionOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.shouldRestoreState, rhs.shouldRestoreState)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AppleConnectionOptions")
    deepHashPrinterConnect(value: shouldRestoreState, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ConnectionPlatformConfig: Hashable {
  var apple: AppleConnectionOptions? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConnectionPlatformConfig? {
    let apple: AppleConnectionOptions? = nilOrValue(pigeonVar_list[0])

    return ConnectionPlatformConfig(
      apple: apple
    )
  }
  func toList() -> [Any?] {
    return [
      apple
    ]
  }
  static func == (lhs: ConnectionPlatformConfig, rhs: ConnectionPlatformConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.apple, rhs.apple)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConnectionPlatformConfig")
    deepHashPrinterConnect(value: apple, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BleConnectionParametersUpdated: Hashable {
  var mtu: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BleConnectionParametersUpdated? {
    let mtu = pigeonVar_list[0] as! Int64

    return BleConnectionParametersUpdated(
      mtu: mtu
    )
  }
  func toList() -> [Any?] {
    return [
      mtu
    ]
  }
  static func == (lhs: BleConnectionParametersUpdated, rhs: BleConnectionParametersUpdated) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrinterConnect(lhs.mtu, rhs.mtu)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BleConnectionParametersUpdated")
    deepHashPrinterConnect(value: mtu, hasher: &hasher)
  }
}

private class PrinterConnectPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BleLogLevel(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AvailabilityState(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BleConnectionState(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BleInputProperty(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BleOutputProperty(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BleConnectionPriority(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AndroidScanMode(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AndroidScanCallbackType(rawValue: enumResultAsInt)
      }
      return nil
    case 137:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AndroidScanMatchMode(rawValue: enumResultAsInt)
      }
      return nil
    case 138:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AndroidScanNumOfMatches(rawValue: enumResultAsInt)
      }
      return nil
    case 139:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CharacteristicProperty(rawValue: enumResultAsInt)
      }
      return nil
    case 140:
      return UniversalBleScanResult.fromList(self.readValue() as! [Any?])
    case 141:
      return UniversalManufacturerData.fromList(self.readValue() as! [Any?])
    case 142:
      return UniversalBleService.fromList(self.readValue() as! [Any?])
    case 143:
      return UniversalBleCharacteristic.fromList(self.readValue() as! [Any?])
    case 144:
      return UniversalBleDescriptor.fromList(self.readValue() as! [Any?])
    case 145:
      return AndroidOptions.fromList(self.readValue() as! [Any?])
    case 146:
      return UniversalScanConfig.fromList(self.readValue() as! [Any?])
    case 147:
      return UniversalScanFilter.fromList(self.readValue() as! [Any?])
    case 148:
      return ManufacturerDataFilter.fromList(self.readValue() as! [Any?])
    case 149:
      return AppleConnectionOptions.fromList(self.readValue() as! [Any?])
    case 150:
      return ConnectionPlatformConfig.fromList(self.readValue() as! [Any?])
    case 151:
      return BleConnectionParametersUpdated.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PrinterConnectPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BleLogLevel {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? AvailabilityState {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? BleConnectionState {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? BleInputProperty {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? BleOutputProperty {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? BleConnectionPriority {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? AndroidScanMode {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? AndroidScanCallbackType {
      super.writeByte(136)
      super.writeValue(value.rawValue)
    } else if let value = value as? AndroidScanMatchMode {
      super.writeByte(137)
      super.writeValue(value.rawValue)
    } else if let value = value as? AndroidScanNumOfMatches {
      super.writeByte(138)
      super.writeValue(value.rawValue)
    } else if let value = value as? CharacteristicProperty {
      super.writeByte(139)
      super.writeValue(value.rawValue)
    } else if let value = value as? UniversalBleScanResult {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? UniversalManufacturerData {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? UniversalBleService {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? UniversalBleCharacteristic {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? UniversalBleDescriptor {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? AndroidOptions {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? UniversalScanConfig {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? UniversalScanFilter {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? ManufacturerDataFilter {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? AppleConnectionOptions {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? ConnectionPlatformConfig {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else if let value = value as? BleConnectionParametersUpdated {
      super.writeByte(151)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PrinterConnectPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PrinterConnectPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PrinterConnectPigeonCodecWriter(data: data)
  }
}

class PrinterConnectPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PrinterConnectPigeonCodec(readerWriter: PrinterConnectPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol UniversalBlePlatformChannel {
  func getBluetoothAvailabilityState(completion: @escaping (Result<AvailabilityState, Error>) -> Void)
  func hasPermissions(completion: @escaping (Result<Bool, Error>) -> Void)
  func requestPermissions(completion: @escaping (Result<Bool, Error>) -> Void)
  func enableBluetooth(completion: @escaping (Result<Void, Error>) -> Void)
  func disableBluetooth(completion: @escaping (Result<Void, Error>) -> Void)
  func startScan(filters: [UniversalScanFilter], androidOptions: AndroidOptions, completion: @escaping (Result<Void, Error>) -> Void)
  func stopScan(completion: @escaping (Result<Void, Error>) -> Void)
  func isScanning(completion: @escaping (Result<Bool, Error>) -> Void)
  func connect(peripheralId: String, config: ConnectionPlatformConfig, completion: @escaping (Result<Void, Error>) -> Void)
  func disconnect(peripheralId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func setNotifiable(peripheralId: String, serviceId: String, characteristicId: String, value: BleInputProperty, completion: @escaping (Result<Void, Error>) -> Void)
  func discoverServices(peripheralId: String, completion: @escaping (Result<[UniversalBleService], Error>) -> Void)
  func readValue(peripheralId: String, serviceId: String, characteristicId: String, completion: @escaping (Result<UniversalBleCharacteristic, Error>) -> Void)
  func requestMtu(peripheralId: String, mtu: Int64, completion: @escaping (Result<Int64, Error>) -> Void)
  func writeValue(peripheralId: String, serviceId: String, characteristicId: String, value: [Int64], bleOutputProperty: BleOutputProperty, completion: @escaping (Result<Void, Error>) -> Void)
  func isPaired(peripheralId: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func pair(peripheralId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func unPair(peripheralId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func getSystemDevices(completion: @escaping (Result<[UniversalBleScanResult], Error>) -> Void)
  func getConnectionState(peripheralId: String, completion: @escaping (Result<BleConnectionState, Error>) -> Void)
  func readRssi(peripheralId: String, completion: @escaping (Result<Int64, Error>) -> Void)
  func requestConnectionPriority(peripheralId: String, priority: BleConnectionPriority, completion: @escaping (Result<Void, Error>) -> Void)
  func setLogLevel(level: BleLogLevel, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class UniversalBlePlatformChannelSetup {
  static var codec: FlutterStandardMessageCodec { PrinterConnectPigeonCodec.shared }
  /// Sets up an instance of `UniversalBlePlatformChannel` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: UniversalBlePlatformChannel?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getBluetoothAvailabilityStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.getBluetoothAvailabilityState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBluetoothAvailabilityStateChannel.setMessageHandler { _, reply in
        api.getBluetoothAvailabilityState { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getBluetoothAvailabilityStateChannel.setMessageHandler(nil)
    }
    let hasPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.hasPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hasPermissionsChannel.setMessageHandler { _, reply in
        api.hasPermissions { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      hasPermissionsChannel.setMessageHandler(nil)
    }
    let requestPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.requestPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionsChannel.setMessageHandler { _, reply in
        api.requestPermissions { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionsChannel.setMessageHandler(nil)
    }
    let enableBluetoothChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.enableBluetooth\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enableBluetoothChannel.setMessageHandler { _, reply in
        api.enableBluetooth { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      enableBluetoothChannel.setMessageHandler(nil)
    }
    let disableBluetoothChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.disableBluetooth\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disableBluetoothChannel.setMessageHandler { _, reply in
        api.disableBluetooth { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disableBluetoothChannel.setMessageHandler(nil)
    }
    let startScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.startScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startScanChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filtersArg = args[0] as! [UniversalScanFilter]
        let androidOptionsArg = args[1] as! AndroidOptions
        api.startScan(filters: filtersArg, androidOptions: androidOptionsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startScanChannel.setMessageHandler(nil)
    }
    let stopScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.stopScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopScanChannel.setMessageHandler { _, reply in
        api.stopScan { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopScanChannel.setMessageHandler(nil)
    }
    let isScanningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.isScanning\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isScanningChannel.setMessageHandler { _, reply in
        api.isScanning { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isScanningChannel.setMessageHandler(nil)
    }
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.connect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let peripheralIdArg = args[0] as! String
        let configArg = args[1] as! ConnectionPlatformConfig
        api.connect(peripheralId: peripheralIdArg, config: configArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.disconnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let peripheralIdArg = args[0] as! String
        api.disconnect(peripheralId: peripheralIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    let setNotifiableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.setNotifiable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setNotifiableChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let peripheralIdArg = args[0] as! String
        let serviceIdArg = args[1] as! String
        let characteristicIdArg = args[2] as! String
        let valueArg = args[3] as! BleInputProperty
        api.setNotifiable(peripheralId: peripheralIdArg, serviceId: serviceIdArg, characteristicId: characteristicIdArg, value: valueArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setNotifiableChannel.setMessageHandler(nil)
    }
    let discoverServicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.discoverServices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      discoverServicesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let peripheralIdArg = args[0] as! String
        api.discoverServices(peripheralId: peripheralIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      discoverServicesChannel.setMessageHandler(nil)
    }
    let readValueChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.readValue\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readValueChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let peripheralIdArg = args[0] as! String
        let serviceIdArg = args[1] as! String
        let characteristicIdArg = args[2] as! String
        api.readValue(peripheralId: peripheralIdArg, serviceId: serviceIdArg, characteristicId: characteristicIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readValueChannel.setMessageHandler(nil)
    }
    let requestMtuChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.requestMtu\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestMtuChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let peripheralIdArg = args[0] as! String
        let mtuArg = args[1] as! Int64
        api.requestMtu(peripheralId: peripheralIdArg, mtu: mtuArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestMtuChannel.setMessageHandler(nil)
    }
    let writeValueChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.writeValue\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      writeValueChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let peripheralIdArg = args[0] as! String
        let serviceIdArg = args[1] as! String
        let characteristicIdArg = args[2] as! String
        let valueArg = args[3] as! [Int64]
        let bleOutputPropertyArg = args[4] as! BleOutputProperty
        api.writeValue(peripheralId: peripheralIdArg, serviceId: serviceIdArg, characteristicId: characteristicIdArg, value: valueArg, bleOutputProperty: bleOutputPropertyArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      writeValueChannel.setMessageHandler(nil)
    }
    let isPairedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.isPaired\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isPairedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let peripheralIdArg = args[0] as! String
        api.isPaired(peripheralId: peripheralIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isPairedChannel.setMessageHandler(nil)
    }
    let pairChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.pair\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pairChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let peripheralIdArg = args[0] as! String
        api.pair(peripheralId: peripheralIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pairChannel.setMessageHandler(nil)
    }
    let unPairChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.unPair\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unPairChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let peripheralIdArg = args[0] as! String
        api.unPair(peripheralId: peripheralIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      unPairChannel.setMessageHandler(nil)
    }
    let getSystemDevicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.getSystemDevices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSystemDevicesChannel.setMessageHandler { _, reply in
        api.getSystemDevices { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getSystemDevicesChannel.setMessageHandler(nil)
    }
    let getConnectionStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.getConnectionState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getConnectionStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let peripheralIdArg = args[0] as! String
        api.getConnectionState(peripheralId: peripheralIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getConnectionStateChannel.setMessageHandler(nil)
    }
    let readRssiChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.readRssi\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readRssiChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let peripheralIdArg = args[0] as! String
        api.readRssi(peripheralId: peripheralIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readRssiChannel.setMessageHandler(nil)
    }
    let requestConnectionPriorityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.requestConnectionPriority\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestConnectionPriorityChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let peripheralIdArg = args[0] as! String
        let priorityArg = args[1] as! BleConnectionPriority
        api.requestConnectionPriority(peripheralId: peripheralIdArg, priority: priorityArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestConnectionPriorityChannel.setMessageHandler(nil)
    }
    let setLogLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.setLogLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLogLevelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let levelArg = args[0] as! BleLogLevel
        api.setLogLevel(level: levelArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setLogLevelChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol UniversalBleCallbackChannelProtocol {
  func onAvailabilityChanged(state stateArg: AvailabilityState, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPairStateChange(peripheralId peripheralIdArg: String, isPaired isPairedArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onScanResult(result resultArg: UniversalBleScanResult, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onValueChanged(peripheralId peripheralIdArg: String, serviceId serviceIdArg: String, characteristicId characteristicIdArg: String, value valueArg: [Int64], completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onConnectionChanged(peripheralId peripheralIdArg: String, state stateArg: BleConnectionState, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onConnectionParametersUpdated(result resultArg: BleConnectionParametersUpdated, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class UniversalBleCallbackChannel: UniversalBleCallbackChannelProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PrinterConnectPigeonCodec {
    return PrinterConnectPigeonCodec.shared
  }
  func onAvailabilityChanged(state stateArg: AvailabilityState, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onAvailabilityChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onPairStateChange(peripheralId peripheralIdArg: String, isPaired isPairedArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onPairStateChange\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([peripheralIdArg, isPairedArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onScanResult(result resultArg: UniversalBleScanResult, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onScanResult\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([resultArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onValueChanged(peripheralId peripheralIdArg: String, serviceId serviceIdArg: String, characteristicId characteristicIdArg: String, value valueArg: [Int64], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onValueChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([peripheralIdArg, serviceIdArg, characteristicIdArg, valueArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onConnectionChanged(peripheralId peripheralIdArg: String, state stateArg: BleConnectionState, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onConnectionChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([peripheralIdArg, stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onConnectionParametersUpdated(result resultArg: BleConnectionParametersUpdated, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onConnectionParametersUpdated\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([resultArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
