//
//  PrinterConnectHelper.swift
//  printer_connect
//

import CoreBluetooth
import Foundation

#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#endif

extension CBCharacteristicProperties {
    var toCharacteristicProperty: [CharacteristicProperty] {
        var properties: [CharacteristicProperty] = []
        if contains(.broadcast) { properties.append(.broadcast) }
        if contains(.read) { properties.append(.read) }
        if contains(.writeWithoutResponse) { properties.append(.writeWithoutResponse) }
        if contains(.write) { properties.append(.write) }
        if contains(.notify) { properties.append(.notify) }
        if contains(.indicate) { properties.append(.indicate) }
        if contains(.authenticatedSignedWrites) { properties.append(.authenticatedSignedWrites) }
        if contains(.extendedProperties) { properties.append(.extendedProperties) }
        return properties
    }
}

extension CBManagerState {
    func toAvailabilityState() -> AvailabilityState {
        switch self {
        case .unknown: return .unknown
        case .resetting: return .resetting
        case .unsupported: return .unsupported
        case .unauthorized: return .unauthorized
        case .poweredOff: return .poweredOff
        case .poweredOn: return .poweredOn
        @unknown default: return .unknown
        }
    }
}

/// Unified error codes for all platforms.
///
/// Mirrors the `UniversalBleErrorCode` enum generated by Pigeon in the
/// reference project. The current project defines this enum manually on each
/// platform (Android in `PrinterConnectPlugin.kt`, Dart in
/// `universal_ble_error_parser.dart`) instead of via Pigeon; this is the iOS
/// counterpart so that `createFlutterError(code:)` / `mapErrorCodeToEnum(_:)`
/// resolve to a concrete type.
enum UniversalBleErrorCode: Int {
    case unknownError = 0
    case failed = 1
    case notSupported = 2
    case notImplemented = 3
    case channelError = 4
    case bluetoothNotAvailable = 5
    case bluetoothNotEnabled = 6
    case bluetoothNotAllowed = 7
    case bluetoothUnauthorized = 8
    case deviceDisconnected = 9
    case connectionTimeout = 10
    case connectionFailed = 11
    case connectionRejected = 12
    case connectionLimitExceeded = 13
    case connectionAlreadyExists = 14
    case connectionTerminated = 15
    case connectionInProgress = 16
    case illegalArgument = 17
    case deviceNotFound = 18
    case serviceNotFound = 19
    case characteristicNotFound = 20
    case invalidServiceUuid = 21
    case invalidCharacteristicUuid = 22
    case invalidOffset = 23
    case invalidAttributeLength = 24
    case invalidPdu = 25
    case invalidHandle = 26
    case readFailed = 27
    case readNotPermitted = 28
    case writeFailed = 29
    case writeNotPermitted = 30
    case writeRequestBusy = 31
    case invalidAction = 32
    case operationNotSupported = 33
    case operationTimeout = 34
    case operationCancelled = 35
    case operationInProgress = 36
    case characteristicDoesNotSupportRead = 37
    case characteristicDoesNotSupportWrite = 38
    case characteristicDoesNotSupportWriteWithoutResponse = 39
    case characteristicDoesNotSupportNotify = 40
    case characteristicDoesNotSupportIndicate = 41
    case notPaired = 42
    case notPairable = 43
    case alreadyPaired = 44
    case pairingFailed = 45
    case pairingCancelled = 46
    case pairingTimeout = 47
    case pairingNotAllowed = 48
    case authenticationFailure = 49
    case insufficientAuthentication = 50
    case insufficientAuthorization = 51
    case insufficientEncryption = 52
    case insufficientKeySize = 53
    case protectionLevelNotMet = 54
    case accessDenied = 55
    case unpairingFailed = 56
    case alreadyUnpaired = 57
    case scanFailed = 58
    case stoppingScanInProgress = 59
    case webBluetoothGloballyDisabled = 60
}

/// Maps string error codes to UniversalBleErrorCode enum
func mapErrorCodeToEnum(_ code: String) -> UniversalBleErrorCode {
    switch code.lowercased() {
    case "notsupported", "not_supported":
        return .notSupported
    case "notimplemented", "not_implemented":
        return .notImplemented
    case "channel-error", "channelerror":
        return .channelError
    case "failed":
        return .failed
    case "devicedisconnected", "device_disconnected":
        return .deviceDisconnected
    case "illegalargument", "illegal_argument":
        return .illegalArgument
    case "invalidaction", "invalid_action":
        return .invalidAction
    case "readfailed", "read_failed":
        return .readFailed
    case "devicenotfound", "device_not_found":
        return .deviceNotFound
    case "servicenotfound", "service_not_found":
        return .serviceNotFound
    case "characteristicnotfound", "characteristic_not_found":
        return .characteristicNotFound
    case "invalidserviceuuid", "invalid_service_uuid":
        return .invalidServiceUuid
    case "characteristicdoesnotsupportread":
        return .characteristicDoesNotSupportRead
    case "characteristicdoesnotsupportwrite":
        return .characteristicDoesNotSupportWrite
    case "characteristicdoesnotsupportwritewithoutresponse":
        return .characteristicDoesNotSupportWriteWithoutResponse
    case "characteristicdoesnotsupportnotify":
        return .characteristicDoesNotSupportNotify
    case "characteristicdoesnotsupportindicate":
        return .characteristicDoesNotSupportIndicate
    default:
        return .unknownError
    }
}

/// Creates a PigeonError with the error code enum in details
func createFlutterError(
    code: UniversalBleErrorCode,
    message: String? = nil,
    details: String? = nil
) -> PigeonError {
    // Pass the enum's rawValue (Int) in code as string, and enum name in details
    return PigeonError(
        code: code.rawValue.description,
        message: message,
        details: details ?? code.rawValue
    )
}

extension Error {
    func toFlutterError() -> PigeonError {
        let nsError = self as NSError
        let errorCode: String = .init(nsError.code)
        let errorDescription: String = nsError.localizedDescription
        let mappedCode = mapErrorCodeToEnum(errorCode)
        return createFlutterError(code: mappedCode, message: errorDescription, details: errorCode)
    }
}

public extension CBUUID {
    var uuidStr: String {
        uuidString.lowercased()
    }
}

public extension CBPeripheral {
    // FIXME: https://forums.developer.apple.com/thread/84375
    var uuid: UUID {
        value(forKey: "identifier") as! NSUUID as UUID
    }

    func getCharacteristic(_ characteristic: String, of service: String) -> CBCharacteristic? {
        let GSS_SUFFIX = "0000-1000-8000-00805f9b34fb"
        let s = services?.first {
            $0.uuid.uuidStr.lowercased() == service.lowercased() || service.lowercased() == "0000\($0.uuid.uuidStr)-\(GSS_SUFFIX)".lowercased()
        }
        let c = s?.characteristics?.first {
            $0.uuid.uuidStr.lowercased() == characteristic.lowercased() || characteristic.lowercased() == "0000\($0.uuid.uuidStr)-\(GSS_SUFFIX)".lowercased()
        }
        return c
    }

    func setNotifiable(_ bleInputProperty: String, for characteristic: String, of service: String) {
        guard let characteristic = getCharacteristic(characteristic, of: service) else {
            return
        }
        setNotifyValue(bleInputProperty != "disabled", for: characteristic)
    }
}

extension FlutterStandardTypedData {
    func toData() -> Data {
        return Data(data)
    }
}

// Future classes
class CharacteristicReadFuture {
    let deviceId: String
    let characteristicId: String
    let serviceId: String?
    let result: (Result<FlutterStandardTypedData, Error>) -> Void

    init(deviceId: String, characteristicId: String, serviceId: String?, result: @escaping (Result<FlutterStandardTypedData, Error>) -> Void) {
        self.deviceId = deviceId
        self.characteristicId = characteristicId
        self.serviceId = serviceId
        self.result = result
    }
}

class CharacteristicWriteFuture {
    let deviceId: String
    let characteristicId: String
    let serviceId: String?
    let result: (Result<Void, Error>) -> Void

    init(deviceId: String, characteristicId: String, serviceId: String?, result: @escaping (Result<Void, Error>) -> Void) {
        self.deviceId = deviceId
        self.characteristicId = characteristicId
        self.serviceId = serviceId
        self.result = result
    }
}

class CharacteristicNotifyFuture {
    let deviceId: String
    let characteristicId: String
    let serviceId: String?
    let result: (Result<Void, Error>) -> Void

    init(deviceId: String, characteristicId: String, serviceId: String?, result: @escaping (Result<Void, Error>) -> Void) {
        self.deviceId = deviceId
        self.characteristicId = characteristicId
        self.serviceId = serviceId
        self.result = result
    }
}

class DiscoverServicesFuture {
    let deviceId: String
    let result: (Result<[UniversalBleService], Error>) -> Void

    init(deviceId: String, result: @escaping (Result<[UniversalBleService], Error>) -> Void) {
        self.deviceId = deviceId
        self.result = result
    }
}

class RssiReadFuture {
    let deviceId: String
    let result: (Result<Int64, Error>) -> Void

    init(deviceId: String, result: @escaping (Result<Int64, Error>) -> Void) {
        self.deviceId = deviceId
        self.result = result
    }
}

extension String {
    func getPeripheral(manager: CBCentralManager) throws -> CBPeripheral {
        guard let peripheral = findPeripheral(manager: manager) else {
            throw createFlutterError(code: .deviceNotFound, message: "Unknown deviceId:\(self)")
        }
        return peripheral
    }

    func findPeripheral(manager: CBCentralManager) -> CBPeripheral? {
        if let peripheral = discoveredPeripherals[self] {
            return peripheral
        }
        if let uuid = UUID(uuidString: self) {
            let peripherals = manager.retrievePeripherals(withIdentifiers: [uuid])
            if let peripheral = peripherals.first {
                discoveredPeripherals[self] = peripheral
                return peripheral
            }
        }
        return nil
    }
}

extension [String] {
    func toCBUUID() throws -> [CBUUID] {
        return try compactMap { serviceUUID in
            guard UUID(uuidString: serviceUUID) != nil else {
                throw createFlutterError(code: .invalidServiceUuid, message: "Invalid service UUID:\(serviceUUID)")
            }
            return CBUUID(string: serviceUUID)
        }
    }
}
