//
//  PrinterConnectHelper.swift
//  printer_connect
//

import CoreBluetooth
import Foundation

#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#endif

extension CBCharacteristicProperties {
    var toCharacteristicProperty: [CharacteristicProperty] {
        var properties: [CharacteristicProperty] = []
        if contains(.broadcast) { properties.append(.broadcast) }
        if contains(.read) { properties.append(.read) }
        if contains(.writeWithoutResponse) { properties.append(.writeWithoutResponse) }
        if contains(.write) { properties.append(.write) }
        if contains(.notify) { properties.append(.notify) }
        if contains(.indicate) { properties.append(.indicate) }
        if contains(.authenticatedSignedWrites) { properties.append(.authenticatedSignedWrites) }
        if contains(.extendedProperties) { properties.append(.extendedProperties) }
        return properties
    }
}

extension CBManagerState {
    func toAvailabilityState() -> AvailabilityState {
        switch self {
        case .unknown: return .unknown
        case .resetting: return .resetting
        case .unsupported: return .unsupported
        case .unauthorized: return .unauthorized
        case .poweredOff: return .poweredOff
        case .poweredOn: return .poweredOn
        @unknown default: return .unknown
        }
    }
}

/// Unified error codes for all platforms.
///
/// Mirrors the `UniversalBleErrorCode` enum generated by Pigeon in the
/// reference project. The numeric values are intentionally aligned with
/// Android's `UniversalBleErrorCode` raw values so that the Dart-side
/// parser (`_parseNumericErrorCode`) can perform a direct index lookup
/// via `UniversalBleErrorCode.values[code]`.
enum UniversalBleErrorCode: Int {
    case unknownError = 0
    case bluetoothNotAvailable = 1
    case bluetoothNotAuthorized = 2
    case bluetoothPermissionDenied = 3
    case bluetoothDisabled = 4
    case bluetoothInvalidState = 5
    case connectionFailed = 6
    case connectionTimeout = 7
    case connectionLost = 8
    case connectionNotEstablished = 9
    case disconnectionFailed = 10
    case writeFailed = 11
    case readFailed = 12
    case discoverServicesFailed = 13
    case setNotifyFailed = 14
    case setIndicateFailed = 15
    case scanFailed = 16
    case scanTimeout = 17
    case deviceNotFound = 18
    case serviceNotFound = 19
    case characteristicNotFound = 20
    case descriptorNotFound = 21
    case invalidValue = 22
    case invalidDeviceId = 23
    case operationCancelled = 24
    case operationNotSupported = 25
    case mtuRequestFailed = 26
    case pairingFailed = 27
    case unpairFailed = 28
    case securityError = 29
    case streamAlreadyListening = 30
    case streamNotListening = 31
    case transactionInProgress = 32
    case invalidTransactionId = 33
    case bluetoothNotEnabled = 34
    case bluetoothNotAllowed = 35
    case notPaired = 36
    case writeNotPermitted = 37
    case writeRequestBusy = 38
    case notImplemented = 39
    case notSupported = 40
    case readNotPermitted = 41
    case insufficientAuthentication = 42
    case insufficientAuthorization = 43
    case insufficientEncryption = 44
    case invalidOffset = 45
    case invalidAttributeLength = 46
    case invalidHandle = 47
    case invalidPdu = 48
    case insufficientKeySize = 49
    case failed = 50
    case operationInProgress = 51
    case connectionInProgress = 52
    case deviceDisconnected = 53
    case characteristicDoesNotSupportWrite = 54
    case characteristicDoesNotSupportWriteWithoutResponse = 55
    case characteristicDoesNotSupportRead = 56
    case characteristicDoesNotSupportNotify = 57
    case characteristicDoesNotSupportIndicate = 58
}

/// Maps error codes (string or numeric) to UniversalBleErrorCode enum.
///
/// CoreBluetooth delivers NSErrors with numeric codes (e.g. CBATTErrorDomain
/// uses codes 0..13). When `toFlutterError` converts the NSError code to a
/// string, this function attempts to parse it as an integer first so that
/// CBATTError / GATT / HCI codes are mapped to the correct
/// `UniversalBleErrorCode`. String fallbacks remain for legacy code paths.
func mapErrorCodeToEnum(_ code: String) -> UniversalBleErrorCode {
    // Try to parse as numeric CoreBluetooth error code first
    if let intCode = Int(code) {
        switch intCode {
        case 0: return .unknownError
        case 1: return .deviceDisconnected // CBATTError.invalidHandle
        case 2: return .readNotPermitted
        case 3: return .writeNotPermitted
        case 4: return .invalidPdu
        case 5: return .insufficientAuthentication
        case 6: return .operationNotSupported // requestNotSupported
        case 7: return .invalidOffset
        case 8: return .insufficientAuthorization
        case 9: return .operationInProgress
        case 10: return .serviceNotFound // attrNotFound
        case 11: return .invalidAttributeLength
        case 12: return .insufficientKeySize
        case 13: return .invalidAttributeLength // attrNotLong
        case 14: return .failed // unlikely
        case 15: return .insufficientEncryption
        case 16: return .operationNotSupported // unsupportedGroup
        case 17: return .failed // insufficientResources
        // HCI codes
        case 0x08, 0x10: return .connectionTimeout
        case 0x09, 0x0A: return .failed // connectionLimitExceeded -> failed
        case 0x0B: return .connectionInProgress
        case 0x0C, 0x11, 0x12, 0x1A, 0x1E, 0x20: return .operationNotSupported
        case 0x0D, 0x0F, 0x39: return .connectionFailed // connectionRejected
        case 0x0E: return .connectionFailed // connectionRejectedDueToSecurity
        case 0x13, 0x14, 0x15, 0x16, 0x3D: return .deviceDisconnected
        case 0x3E, 0x3F: return .connectionFailed
        case 0x05: return .insufficientAuthentication // authenticationFailure
        case 0x18: return .notPaired
        case 0x22: return .operationNotSupported // lmpResponseTimeout
        default: break
        }
    }

    // String-based fallback for legacy code paths
    switch code.lowercased() {
    case "notsupported", "not_supported":
        return .notSupported
    case "notimplemented", "not_implemented":
        return .notImplemented
    case "channel-error", "channelerror":
        return .unknownError // channelError mapped to unknownError in aligned scheme
    case "failed":
        return .failed
    case "devicedisconnected", "device_disconnected":
        return .deviceDisconnected
    case "illegalargument", "illegal_argument":
        return .invalidValue // illegalArgument -> invalidValue
    case "invalidaction", "invalid_action":
        return .invalidValue
    case "readfailed", "read_failed":
        return .readFailed
    case "devicenotfound", "device_not_found":
        return .deviceNotFound
    case "servicenotfound", "service_not_found":
        return .serviceNotFound
    case "characteristicnotfound", "characteristic_not_found":
        return .characteristicNotFound
    case "invalidserviceuuid", "invalid_service_uuid":
        return .invalidValue // invalidServiceUuid -> invalidValue
    case "characteristicdoesnotsupportread":
        return .characteristicDoesNotSupportRead
    case "characteristicdoesnotsupportwrite":
        return .characteristicDoesNotSupportWrite
    case "characteristicdoesnotsupportwritewithoutresponse":
        return .characteristicDoesNotSupportWriteWithoutResponse
    case "characteristicdoesnotsupportnotify":
        return .characteristicDoesNotSupportNotify
    case "characteristicdoesnotsupportindicate":
        return .characteristicDoesNotSupportIndicate
    default:
        return .unknownError
    }
}

/// Creates a PigeonError with the error code enum in details
func createFlutterError(
    code: UniversalBleErrorCode,
    message: String? = nil,
    details: String? = nil
) -> PigeonError {
    // Pass the enum's rawValue (Int) in code as string, and enum name in details
    return PigeonError(
        code: code.rawValue.description,
        message: message,
        details: details ?? code.rawValue
    )
}

extension Error {
    func toFlutterError() -> PigeonError {
        let nsError = self as NSError
        let errorCode: String = .init(nsError.code)
        let errorDescription: String = nsError.localizedDescription
        let mappedCode = mapErrorCodeToEnum(errorCode)
        return createFlutterError(code: mappedCode, message: errorDescription, details: errorCode)
    }
}

public extension CBUUID {
    var uuidStr: String {
        uuidString.lowercased()
    }
}

public extension CBPeripheral {
    // FIXME: https://forums.developer.apple.com/thread/84375
    var uuid: UUID {
        value(forKey: "identifier") as! NSUUID as UUID
    }

    func getCharacteristic(_ characteristic: String, of service: String) -> CBCharacteristic? {
        let GSS_SUFFIX = "0000-1000-8000-00805f9b34fb"
        let s = services?.first {
            $0.uuid.uuidStr.lowercased() == service.lowercased() || service.lowercased() == "0000\($0.uuid.uuidStr)-\(GSS_SUFFIX)".lowercased()
        }
        let c = s?.characteristics?.first {
            $0.uuid.uuidStr.lowercased() == characteristic.lowercased() || characteristic.lowercased() == "0000\($0.uuid.uuidStr)-\(GSS_SUFFIX)".lowercased()
        }
        return c
    }

    func setNotifiable(_ bleInputProperty: String, for characteristic: String, of service: String) {
        guard let characteristic = getCharacteristic(characteristic, of: service) else {
            return
        }
        setNotifyValue(bleInputProperty != "disabled", for: characteristic)
    }
}

extension FlutterStandardTypedData {
    func toData() -> Data {
        return Data(data)
    }
}

// Future classes
class CharacteristicReadFuture {
    let deviceId: String
    let characteristicId: String
    let serviceId: String?
    let result: (Result<FlutterStandardTypedData, Error>) -> Void

    init(deviceId: String, characteristicId: String, serviceId: String?, result: @escaping (Result<FlutterStandardTypedData, Error>) -> Void) {
        self.deviceId = deviceId
        self.characteristicId = characteristicId
        self.serviceId = serviceId
        self.result = result
    }
}

class CharacteristicWriteFuture {
    let deviceId: String
    let characteristicId: String
    let serviceId: String?
    let result: (Result<Void, Error>) -> Void

    init(deviceId: String, characteristicId: String, serviceId: String?, result: @escaping (Result<Void, Error>) -> Void) {
        self.deviceId = deviceId
        self.characteristicId = characteristicId
        self.serviceId = serviceId
        self.result = result
    }
}

class CharacteristicNotifyFuture {
    let deviceId: String
    let characteristicId: String
    let serviceId: String?
    let result: (Result<Void, Error>) -> Void

    init(deviceId: String, characteristicId: String, serviceId: String?, result: @escaping (Result<Void, Error>) -> Void) {
        self.deviceId = deviceId
        self.characteristicId = characteristicId
        self.serviceId = serviceId
        self.result = result
    }
}

class DiscoverServicesFuture {
    let deviceId: String
    let result: (Result<[UniversalBleService], Error>) -> Void

    init(deviceId: String, result: @escaping (Result<[UniversalBleService], Error>) -> Void) {
        self.deviceId = deviceId
        self.result = result
    }
}

class RssiReadFuture {
    let deviceId: String
    let result: (Result<Int64, Error>) -> Void

    init(deviceId: String, result: @escaping (Result<Int64, Error>) -> Void) {
        self.deviceId = deviceId
        self.result = result
    }
}

extension String {
    func getPeripheral(manager: CBCentralManager) throws -> CBPeripheral {
        guard let peripheral = findPeripheral(manager: manager) else {
            throw createFlutterError(code: .deviceNotFound, message: "Unknown deviceId:\(self)")
        }
        return peripheral
    }

    func findPeripheral(manager: CBCentralManager) -> CBPeripheral? {
        if let peripheral = discoveredPeripherals[self] {
            return peripheral
        }
        if let uuid = UUID(uuidString: self) {
            let peripherals = manager.retrievePeripherals(withIdentifiers: [uuid])
            if let peripheral = peripherals.first {
                discoveredPeripherals[self] = peripheral
                return peripheral
            }
        }
        return nil
    }
}

extension [String] {
    func toCBUUID() throws -> [CBUUID] {
        return try compactMap { serviceUUID in
            guard UUID(uuidString: serviceUUID) != nil else {
                throw createFlutterError(code: .invalidValue, message: "Invalid service UUID:\(serviceUUID)")
            }
            return CBUUID(string: serviceUUID)
        }
    }
}
