// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum BleLogLevel { none, error, warning, info, debug, verbose }

enum AvailabilityState {
  unknown,
  resetting,
  unsupported,
  unauthorized,
  poweredOff,
  poweredOn,
}

enum BleConnectionState { connected, disconnected, connecting, disconnecting }

enum BleInputProperty { disabled, notification, indication }

enum BleOutputProperty { withResponse, withoutResponse }

enum BleConnectionPriority { balanced, highPerformance, lowPower }

enum AndroidScanMode { balanced, lowLatency, lowPower, opportunistic }

enum AndroidScanCallbackType {
  allMatches,
  firstMatch,
  matchLost,
  allMatchesAutoBatch,
}

enum AndroidScanMatchMode { aggressive, sticky }

enum AndroidScanNumOfMatches { one, few, max }

enum CharacteristicProperty {
  broadcast,
  read,
  writeWithoutResponse,
  write,
  notify,
  indicate,
  authenticatedSignedWrites,
  extendedProperties,
}

class UniversalBleScanResult {
  UniversalBleScanResult({
    required this.deviceId,
    this.name,
    this.isPaired,
    this.rssi,
    this.manufacturerDataList,
    this.serviceData,
    this.services,
    this.timestamp,
  });

  String deviceId;

  String? name;

  bool? isPaired;

  int? rssi;

  List<UniversalManufacturerData>? manufacturerDataList;

  Map<String, Uint8List>? serviceData;

  List<String>? services;

  int? timestamp;

  List<Object?> _toList() {
    return <Object?>[
      deviceId,
      name,
      isPaired,
      rssi,
      manufacturerDataList,
      serviceData,
      services,
      timestamp,
    ];
  }

  Object encode() {
    return _toList();
  }

  static UniversalBleScanResult decode(Object result) {
    result as List<Object?>;
    return UniversalBleScanResult(
      deviceId: result[0]! as String,
      name: result[1] as String?,
      isPaired: result[2] as bool?,
      rssi: result[3] as int?,
      manufacturerDataList: (result[4] as List<Object?>?)
          ?.cast<UniversalManufacturerData>(),
      serviceData: (result[5] as Map<Object?, Object?>?)
          ?.cast<String, Uint8List>(),
      services: (result[6] as List<Object?>?)?.cast<String>(),
      timestamp: result[7] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UniversalBleScanResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) &&
        _deepEquals(name, other.name) &&
        _deepEquals(isPaired, other.isPaired) &&
        _deepEquals(rssi, other.rssi) &&
        _deepEquals(manufacturerDataList, other.manufacturerDataList) &&
        _deepEquals(serviceData, other.serviceData) &&
        _deepEquals(services, other.services) &&
        _deepEquals(timestamp, other.timestamp);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class UniversalBleService {
  UniversalBleService({required this.uuid, this.characteristics});

  String uuid;

  List<UniversalBleCharacteristic>? characteristics;

  List<Object?> _toList() {
    return <Object?>[uuid, characteristics];
  }

  Object encode() {
    return _toList();
  }

  static UniversalBleService decode(Object result) {
    result as List<Object?>;
    return UniversalBleService(
      uuid: result[0]! as String,
      characteristics: (result[1] as List<Object?>?)
          ?.cast<UniversalBleCharacteristic>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UniversalBleService || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uuid, other.uuid) &&
        _deepEquals(characteristics, other.characteristics);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class UniversalBleCharacteristic {
  UniversalBleCharacteristic({
    required this.uuid,
    required this.properties,
    required this.descriptors,
  });

  String uuid;

  List<CharacteristicProperty> properties;

  List<UniversalBleDescriptor> descriptors;

  List<Object?> _toList() {
    return <Object?>[uuid, properties, descriptors];
  }

  Object encode() {
    return _toList();
  }

  static UniversalBleCharacteristic decode(Object result) {
    result as List<Object?>;
    return UniversalBleCharacteristic(
      uuid: result[0]! as String,
      properties: (result[1]! as List<Object?>).cast<CharacteristicProperty>(),
      descriptors: (result[2]! as List<Object?>).cast<UniversalBleDescriptor>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UniversalBleCharacteristic ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uuid, other.uuid) &&
        _deepEquals(properties, other.properties) &&
        _deepEquals(descriptors, other.descriptors);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class UniversalBleDescriptor {
  UniversalBleDescriptor({required this.uuid});

  String uuid;

  List<Object?> _toList() {
    return <Object?>[uuid];
  }

  Object encode() {
    return _toList();
  }

  static UniversalBleDescriptor decode(Object result) {
    result as List<Object?>;
    return UniversalBleDescriptor(uuid: result[0]! as String);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UniversalBleDescriptor || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uuid, other.uuid);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class BleConnectionParametersUpdated {
  BleConnectionParametersUpdated({
    required this.deviceId,
    required this.interval,
    required this.latency,
    required this.supervisionTimeout,
    required this.status,
  });

  String deviceId;

  int interval;

  int latency;

  int supervisionTimeout;

  int status;

  List<Object?> _toList() {
    return <Object?>[deviceId, interval, latency, supervisionTimeout, status];
  }

  Object encode() {
    return _toList();
  }

  static BleConnectionParametersUpdated decode(Object result) {
    result as List<Object?>;
    return BleConnectionParametersUpdated(
      deviceId: result[0]! as String,
      interval: result[1]! as int,
      latency: result[2]! as int,
      supervisionTimeout: result[3]! as int,
      status: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BleConnectionParametersUpdated ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) &&
        _deepEquals(interval, other.interval) &&
        _deepEquals(latency, other.latency) &&
        _deepEquals(supervisionTimeout, other.supervisionTimeout) &&
        _deepEquals(status, other.status);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class AndroidOptions {
  AndroidOptions({
    this.requestLocationPermission,
    this.scanMode,
    this.reportDelayMillis,
    this.callbackType,
    this.matchMode,
    this.numOfMatches,
    this.legacy,
  });

  bool? requestLocationPermission;

  AndroidScanMode? scanMode;

  int? reportDelayMillis;

  List<AndroidScanCallbackType>? callbackType;

  AndroidScanMatchMode? matchMode;

  AndroidScanNumOfMatches? numOfMatches;

  bool? legacy;

  List<Object?> _toList() {
    return <Object?>[
      requestLocationPermission,
      scanMode,
      reportDelayMillis,
      callbackType,
      matchMode,
      numOfMatches,
      legacy,
    ];
  }

  Object encode() {
    return _toList();
  }

  static AndroidOptions decode(Object result) {
    result as List<Object?>;
    return AndroidOptions(
      requestLocationPermission: result[0] as bool?,
      scanMode: result[1] as AndroidScanMode?,
      reportDelayMillis: result[2] as int?,
      callbackType: (result[3] as List<Object?>?)
          ?.cast<AndroidScanCallbackType>(),
      matchMode: result[4] as AndroidScanMatchMode?,
      numOfMatches: result[5] as AndroidScanNumOfMatches?,
      legacy: result[6] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(
          requestLocationPermission,
          other.requestLocationPermission,
        ) &&
        _deepEquals(scanMode, other.scanMode) &&
        _deepEquals(reportDelayMillis, other.reportDelayMillis) &&
        _deepEquals(callbackType, other.callbackType) &&
        _deepEquals(matchMode, other.matchMode) &&
        _deepEquals(numOfMatches, other.numOfMatches) &&
        _deepEquals(legacy, other.legacy);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class UniversalScanConfig {
  UniversalScanConfig({this.android});

  AndroidOptions? android;

  List<Object?> _toList() {
    return <Object?>[android];
  }

  Object encode() {
    return _toList();
  }

  static UniversalScanConfig decode(Object result) {
    result as List<Object?>;
    return UniversalScanConfig(android: result[0] as AndroidOptions?);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UniversalScanConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(android, other.android);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class UniversalScanFilter {
  UniversalScanFilter({
    required this.withServices,
    required this.withNamePrefix,
    required this.withManufacturerData,
  });

  List<String> withServices;

  List<String> withNamePrefix;

  List<ManufacturerDataFilter> withManufacturerData;

  List<Object?> _toList() {
    return <Object?>[withServices, withNamePrefix, withManufacturerData];
  }

  Object encode() {
    return _toList();
  }

  static UniversalScanFilter decode(Object result) {
    result as List<Object?>;
    return UniversalScanFilter(
      withServices: (result[0]! as List<Object?>).cast<String>(),
      withNamePrefix: (result[1]! as List<Object?>).cast<String>(),
      withManufacturerData: (result[2]! as List<Object?>)
          .cast<ManufacturerDataFilter>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UniversalScanFilter || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(withServices, other.withServices) &&
        _deepEquals(withNamePrefix, other.withNamePrefix) &&
        _deepEquals(withManufacturerData, other.withManufacturerData);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class ManufacturerDataFilter {
  ManufacturerDataFilter({
    required this.companyIdentifier,
    this.payloadPrefix,
    this.payloadMask,
  });

  int companyIdentifier;

  Uint8List? payloadPrefix;

  Uint8List? payloadMask;

  List<Object?> _toList() {
    return <Object?>[companyIdentifier, payloadPrefix, payloadMask];
  }

  Object encode() {
    return _toList();
  }

  static ManufacturerDataFilter decode(Object result) {
    result as List<Object?>;
    return ManufacturerDataFilter(
      companyIdentifier: result[0]! as int,
      payloadPrefix: result[1] as Uint8List?,
      payloadMask: result[2] as Uint8List?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ManufacturerDataFilter || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(companyIdentifier, other.companyIdentifier) &&
        _deepEquals(payloadPrefix, other.payloadPrefix) &&
        _deepEquals(payloadMask, other.payloadMask);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class UniversalManufacturerData {
  UniversalManufacturerData({
    required this.companyIdentifier,
    required this.data,
  });

  int companyIdentifier;

  Uint8List data;

  List<Object?> _toList() {
    return <Object?>[companyIdentifier, data];
  }

  Object encode() {
    return _toList();
  }

  static UniversalManufacturerData decode(Object result) {
    result as List<Object?>;
    return UniversalManufacturerData(
      companyIdentifier: result[0]! as int,
      data: result[1]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UniversalManufacturerData ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(companyIdentifier, other.companyIdentifier) &&
        _deepEquals(data, other.data);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class AppleConnectionOptions {
  AppleConnectionOptions({
    this.notifyOnConnection,
    this.notifyOnDisconnection,
    this.notifyOnNotification,
  });

  bool? notifyOnConnection;

  bool? notifyOnDisconnection;

  bool? notifyOnNotification;

  List<Object?> _toList() {
    return <Object?>[
      notifyOnConnection,
      notifyOnDisconnection,
      notifyOnNotification,
    ];
  }

  Object encode() {
    return _toList();
  }

  static AppleConnectionOptions decode(Object result) {
    result as List<Object?>;
    return AppleConnectionOptions(
      notifyOnConnection: result[0] as bool?,
      notifyOnDisconnection: result[1] as bool?,
      notifyOnNotification: result[2] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleConnectionOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(notifyOnConnection, other.notifyOnConnection) &&
        _deepEquals(notifyOnDisconnection, other.notifyOnDisconnection) &&
        _deepEquals(notifyOnNotification, other.notifyOnNotification);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class ConnectionPlatformConfig {
  ConnectionPlatformConfig({this.apple});

  AppleConnectionOptions? apple;

  List<Object?> _toList() {
    return <Object?>[apple];
  }

  Object encode() {
    return _toList();
  }

  static ConnectionPlatformConfig decode(Object result) {
    result as List<Object?>;
    return ConnectionPlatformConfig(
      apple: result[0] as AppleConnectionOptions?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConnectionPlatformConfig ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(apple, other.apple);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is BleLogLevel) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is AvailabilityState) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is BleConnectionState) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is BleInputProperty) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is BleOutputProperty) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is BleConnectionPriority) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    } else if (value is AndroidScanMode) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    } else if (value is AndroidScanCallbackType) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    } else if (value is AndroidScanMatchMode) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    } else if (value is AndroidScanNumOfMatches) {
      buffer.putUint8(138);
      writeValue(buffer, value.index);
    } else if (value is CharacteristicProperty) {
      buffer.putUint8(139);
      writeValue(buffer, value.index);
    } else if (value is UniversalBleScanResult) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is UniversalBleService) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is UniversalBleCharacteristic) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is UniversalBleDescriptor) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is BleConnectionParametersUpdated) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is AndroidOptions) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is UniversalScanConfig) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is UniversalScanFilter) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else if (value is ManufacturerDataFilter) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    } else if (value is UniversalManufacturerData) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    } else if (value is AppleConnectionOptions) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    } else if (value is ConnectionPlatformConfig) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : BleLogLevel.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : AvailabilityState.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : BleConnectionState.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : BleInputProperty.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : BleOutputProperty.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : BleConnectionPriority.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidScanMode.values[value];
      case 136:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidScanCallbackType.values[value];
      case 137:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidScanMatchMode.values[value];
      case 138:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidScanNumOfMatches.values[value];
      case 139:
        final value = readValue(buffer) as int?;
        return value == null ? null : CharacteristicProperty.values[value];
      case 140:
        return UniversalBleScanResult.decode(readValue(buffer)!);
      case 141:
        return UniversalBleService.decode(readValue(buffer)!);
      case 142:
        return UniversalBleCharacteristic.decode(readValue(buffer)!);
      case 143:
        return UniversalBleDescriptor.decode(readValue(buffer)!);
      case 144:
        return BleConnectionParametersUpdated.decode(readValue(buffer)!);
      case 145:
        return AndroidOptions.decode(readValue(buffer)!);
      case 146:
        return UniversalScanConfig.decode(readValue(buffer)!);
      case 147:
        return UniversalScanFilter.decode(readValue(buffer)!);
      case 148:
        return ManufacturerDataFilter.decode(readValue(buffer)!);
      case 149:
        return UniversalManufacturerData.decode(readValue(buffer)!);
      case 150:
        return AppleConnectionOptions.decode(readValue(buffer)!);
      case 151:
        return ConnectionPlatformConfig.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class UniversalBlePlatformChannel {
  /// Constructor for [UniversalBlePlatformChannel].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  UniversalBlePlatformChannel({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<AvailabilityState> getBluetoothAvailabilityState() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.getBluetoothAvailabilityState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as AvailabilityState;
  }

  Future<bool> hasPermissions(bool withAndroidFineLocation) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.hasPermissions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[withAndroidFineLocation],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<void> requestPermissions(bool withAndroidFineLocation) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.requestPermissions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[withAndroidFineLocation],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<bool> enableBluetooth() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.enableBluetooth$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> disableBluetooth() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.disableBluetooth$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<void> startScan(
    UniversalScanFilter? filter,
    UniversalScanConfig? config,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.startScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[filter, config],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> stopScan() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.stopScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<bool> isScanning() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.isScanning$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<void> connect(
    String deviceId, {
    bool? autoConnect,
    ConnectionPlatformConfig? platformConfig,
  }) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.connect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, autoConnect, platformConfig],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> disconnect(String deviceId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.disconnect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setNotifiable(
    String deviceId,
    String service,
    String characteristic,
    BleInputProperty bleInputProperty,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.setNotifiable$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, service, characteristic, bleInputProperty],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<List<UniversalBleService>> discoverServices(
    String deviceId,
    bool withDescriptors,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.discoverServices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, withDescriptors],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<UniversalBleService>();
  }

  Future<Uint8List> readValue(
    String deviceId,
    String service,
    String characteristic,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.readValue$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, service, characteristic],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as Uint8List;
  }

  Future<int> requestMtu(String deviceId, int expectedMtu) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.requestMtu$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, expectedMtu],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  Future<void> writeValue(
    String deviceId,
    String service,
    String characteristic,
    Uint8List value,
    BleOutputProperty bleOutputProperty,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.writeValue$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, service, characteristic, value, bleOutputProperty],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<bool> isPaired(String deviceId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.isPaired$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> pair(String deviceId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.pair$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<void> unPair(String deviceId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.unPair$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<List<UniversalBleScanResult>> getSystemDevices(
    List<String> withServices,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.getSystemDevices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[withServices],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>)
        .cast<UniversalBleScanResult>();
  }

  Future<BleConnectionState> getConnectionState(String deviceId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.getConnectionState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as BleConnectionState;
  }

  Future<int> readRssi(String deviceId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.readRssi$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  Future<void> requestConnectionPriority(
    String deviceId,
    BleConnectionPriority priority,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.requestConnectionPriority$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, priority],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setLogLevel(BleLogLevel logLevel) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.setLogLevel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[logLevel],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

abstract class UniversalBleCallbackChannel {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onAvailabilityChanged(AvailabilityState state);

  void onPairStateChange(String deviceId, bool isPaired, String? error);

  void onScanResult(UniversalBleScanResult result);

  void onValueChanged(
    String deviceId,
    String characteristicId,
    Uint8List value,
    int? timestamp,
  );

  void onConnectionChanged(String deviceId, bool connected, String? error);

  void onConnectionParametersUpdated(BleConnectionParametersUpdated update);

  static void setUp(
    UniversalBleCallbackChannel? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onAvailabilityChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AvailabilityState arg_state = args[0]! as AvailabilityState;
          try {
            api.onAvailabilityChanged(arg_state);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onPairStateChange$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_deviceId = args[0]! as String;
          final bool arg_isPaired = args[1]! as bool;
          final String? arg_error = args[2] as String?;
          try {
            api.onPairStateChange(arg_deviceId, arg_isPaired, arg_error);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onScanResult$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final UniversalBleScanResult arg_result =
              args[0]! as UniversalBleScanResult;
          try {
            api.onScanResult(arg_result);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onValueChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_deviceId = args[0]! as String;
          final String arg_characteristicId = args[1]! as String;
          final Uint8List arg_value = args[2]! as Uint8List;
          final int? arg_timestamp = args[3] as int?;
          try {
            api.onValueChanged(
              arg_deviceId,
              arg_characteristicId,
              arg_value,
              arg_timestamp,
            );
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onConnectionChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_deviceId = args[0]! as String;
          final bool arg_connected = args[1]! as bool;
          final String? arg_error = args[2] as String?;
          try {
            api.onConnectionChanged(arg_deviceId, arg_connected, arg_error);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onConnectionParametersUpdated$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final BleConnectionParametersUpdated arg_update =
              args[0]! as BleConnectionParametersUpdated;
          try {
            api.onConnectionParametersUpdated(arg_update);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
