// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum BleLogLevel {
  verbose,
  debug,
  info,
  warning,
  error,
  wtf,
  none,
}

enum AvailabilityState {
  unknown,
  resetting,
  unsupported,
  unauthorized,
  poweredOff,
  poweredOn,
}

enum BleConnectionState {
  disconnected,
  connecting,
  connected,
  disconnecting,
}

enum BleInputProperty {
  disabled,
  notification,
  indication,
}

enum BleOutputProperty {
  none,
  write,
  writeWithoutResponse,
}

enum BleConnectionPriority {
  balanced,
  highPerformance,
  lowPower,
}

enum AndroidScanMode {
  lowPowered,
  balanced,
  lowLatency,
}

enum AndroidScanCallbackType {
  default_,
  firstMatch,
  lose,
  matched,
}

enum AndroidScanMatchMode {
  default_,
  sticky,
}

enum AndroidScanNumOfMatches {
  one,
  few,
  many,
}

enum CharacteristicProperty {
  read,
  write,
  writeWithoutResponse,
  notify,
  indicate,
  broadcast,
  extendedSbleProps,
  signedWrite,
}

class UniversalBleScanResult {
  UniversalBleScanResult({
    required this.peripheralId,
    this.name,
    required this.rssi,
    this.manufacturerData,
    this.serviceData,
    this.serviceUuids,
    this.txPowerLevel,
  });

  String peripheralId;

  String? name;

  int rssi;

  List<UniversalManufacturerData>? manufacturerData;

  List<int>? serviceData;

  List<String>? serviceUuids;

  int? txPowerLevel;

  List<Object?> _toList() {
    return <Object?>[
      peripheralId,
      name,
      rssi,
      manufacturerData,
      serviceData,
      serviceUuids,
      txPowerLevel,
    ];
  }

  Object encode() {
    return _toList();  }

  static UniversalBleScanResult decode(Object result) {
    result as List<Object?>;
    return UniversalBleScanResult(
      peripheralId: result[0]! as String,
      name: result[1] as String?,
      rssi: result[2]! as int,
      manufacturerData: (result[3] as List<Object?>?)?.cast<UniversalManufacturerData>(),
      serviceData: (result[4] as List<Object?>?)?.cast<int>(),
      serviceUuids: (result[5] as List<Object?>?)?.cast<String>(),
      txPowerLevel: result[6] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UniversalBleScanResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(peripheralId, other.peripheralId) && _deepEquals(name, other.name) && _deepEquals(rssi, other.rssi) && _deepEquals(manufacturerData, other.manufacturerData) && _deepEquals(serviceData, other.serviceData) && _deepEquals(serviceUuids, other.serviceUuids) && _deepEquals(txPowerLevel, other.txPowerLevel);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class UniversalManufacturerData {
  UniversalManufacturerData({
    required this.id,
    required this.data,
  });

  int id;

  List<int> data;

  List<Object?> _toList() {
    return <Object?>[
      id,
      data,
    ];
  }

  Object encode() {
    return _toList();  }

  static UniversalManufacturerData decode(Object result) {
    result as List<Object?>;
    return UniversalManufacturerData(
      id: result[0]! as int,
      data: (result[1]! as List<Object?>).cast<int>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UniversalManufacturerData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(data, other.data);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class UniversalBleService {
  UniversalBleService({
    required this.uuid,
    required this.isPrimary,
  });

  String uuid;

  bool isPrimary;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      isPrimary,
    ];
  }

  Object encode() {
    return _toList();  }

  static UniversalBleService decode(Object result) {
    result as List<Object?>;
    return UniversalBleService(
      uuid: result[0]! as String,
      isPrimary: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UniversalBleService || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uuid, other.uuid) && _deepEquals(isPrimary, other.isPrimary);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class UniversalBleCharacteristic {
  UniversalBleCharacteristic({
    required this.uuid,
    required this.properties,
    this.value,
  });

  String uuid;

  List<CharacteristicProperty> properties;

  List<int>? value;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      properties,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static UniversalBleCharacteristic decode(Object result) {
    result as List<Object?>;
    return UniversalBleCharacteristic(
      uuid: result[0]! as String,
      properties: (result[1]! as List<Object?>).cast<CharacteristicProperty>(),
      value: (result[2] as List<Object?>?)?.cast<int>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UniversalBleCharacteristic || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uuid, other.uuid) && _deepEquals(properties, other.properties) && _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class UniversalBleDescriptor {
  UniversalBleDescriptor({
    required this.uuid,
    this.value,
  });

  String uuid;

  List<int>? value;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static UniversalBleDescriptor decode(Object result) {
    result as List<Object?>;
    return UniversalBleDescriptor(
      uuid: result[0]! as String,
      value: (result[1] as List<Object?>?)?.cast<int>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UniversalBleDescriptor || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uuid, other.uuid) && _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class AndroidOptions {
  AndroidOptions({
    this.scanMode,
    this.callbackType,
    this.matchMode,
    this.numOfMatches,
  });

  AndroidScanMode? scanMode;

  AndroidScanCallbackType? callbackType;

  AndroidScanMatchMode? matchMode;

  AndroidScanNumOfMatches? numOfMatches;

  List<Object?> _toList() {
    return <Object?>[
      scanMode,
      callbackType,
      matchMode,
      numOfMatches,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidOptions decode(Object result) {
    result as List<Object?>;
    return AndroidOptions(
      scanMode: result[0] as AndroidScanMode?,
      callbackType: result[1] as AndroidScanCallbackType?,
      matchMode: result[2] as AndroidScanMatchMode?,
      numOfMatches: result[3] as AndroidScanNumOfMatches?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(scanMode, other.scanMode) && _deepEquals(callbackType, other.callbackType) && _deepEquals(matchMode, other.matchMode) && _deepEquals(numOfMatches, other.numOfMatches);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class UniversalScanConfig {
  UniversalScanConfig({
    this.scanFilters,
    this.androidOptions,
  });

  List<UniversalScanFilter>? scanFilters;

  AndroidOptions? androidOptions;

  List<Object?> _toList() {
    return <Object?>[
      scanFilters,
      androidOptions,
    ];
  }

  Object encode() {
    return _toList();  }

  static UniversalScanConfig decode(Object result) {
    result as List<Object?>;
    return UniversalScanConfig(
      scanFilters: (result[0] as List<Object?>?)?.cast<UniversalScanFilter>(),
      androidOptions: result[1] as AndroidOptions?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UniversalScanConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(scanFilters, other.scanFilters) && _deepEquals(androidOptions, other.androidOptions);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class UniversalScanFilter {
  UniversalScanFilter({
    this.withServices,
    this.withManufacturerData,
    this.withLocalName,
    this.withLocalNamePrefix,
    this.withDeviceId,
    this.exclusionFilters,
  });

  List<String>? withServices;

  List<ManufacturerDataFilter>? withManufacturerData;

  String? withLocalName;

  List<String>? withLocalNamePrefix;

  List<String>? withDeviceId;

  List<UniversalScanFilter>? exclusionFilters;

  List<Object?> _toList() {
    return <Object?>[
      withServices,
      withManufacturerData,
      withLocalName,
      withLocalNamePrefix,
      withDeviceId,
      exclusionFilters,
    ];
  }

  Object encode() {
    return _toList();  }

  static UniversalScanFilter decode(Object result) {
    result as List<Object?>;
    return UniversalScanFilter(
      withServices: (result[0] as List<Object?>?)?.cast<String>(),
      withManufacturerData: (result[1] as List<Object?>?)?.cast<ManufacturerDataFilter>(),
      withLocalName: result[2] as String?,
      withLocalNamePrefix: (result[3] as List<Object?>?)?.cast<String>(),
      withDeviceId: (result[4] as List<Object?>?)?.cast<String>(),
      exclusionFilters: (result[5] as List<Object?>?)?.cast<UniversalScanFilter>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UniversalScanFilter || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(withServices, other.withServices) && _deepEquals(withManufacturerData, other.withManufacturerData) && _deepEquals(withLocalName, other.withLocalName) && _deepEquals(withLocalNamePrefix, other.withLocalNamePrefix) && _deepEquals(withDeviceId, other.withDeviceId) && _deepEquals(exclusionFilters, other.exclusionFilters);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class ManufacturerDataFilter {
  ManufacturerDataFilter({
    required this.companyId,
    this.data,
    this.mask,
  });

  int companyId;

  List<int>? data;

  List<int>? mask;

  List<Object?> _toList() {
    return <Object?>[
      companyId,
      data,
      mask,
    ];
  }

  Object encode() {
    return _toList();  }

  static ManufacturerDataFilter decode(Object result) {
    result as List<Object?>;
    return ManufacturerDataFilter(
      companyId: result[0]! as int,
      data: (result[1] as List<Object?>?)?.cast<int>(),
      mask: (result[2] as List<Object?>?)?.cast<int>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ManufacturerDataFilter || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(companyId, other.companyId) && _deepEquals(data, other.data) && _deepEquals(mask, other.mask);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class AppleConnectionOptions {
  AppleConnectionOptions({
    this.shouldRestoreState,
    this.notifyOnConnection,
    this.notifyOnDisconnection,
    this.notifyOnNotification,
  });

  bool? shouldRestoreState;

  bool? notifyOnConnection;

  bool? notifyOnDisconnection;

  bool? notifyOnNotification;

  List<Object?> _toList() {
    return <Object?>[
      shouldRestoreState,
      notifyOnConnection,
      notifyOnDisconnection,
      notifyOnNotification,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleConnectionOptions decode(Object result) {
    result as List<Object?>;
    return AppleConnectionOptions(
      shouldRestoreState: result[0] as bool?,
      notifyOnConnection: result[1] as bool?,
      notifyOnDisconnection: result[2] as bool?,
      notifyOnNotification: result[3] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleConnectionOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(shouldRestoreState, other.shouldRestoreState) && _deepEquals(notifyOnConnection, other.notifyOnConnection) && _deepEquals(notifyOnDisconnection, other.notifyOnDisconnection) && _deepEquals(notifyOnNotification, other.notifyOnNotification);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class ConnectionPlatformConfig {
  ConnectionPlatformConfig({
    this.apple,
  });

  AppleConnectionOptions? apple;

  List<Object?> _toList() {
    return <Object?>[
      apple,
    ];
  }

  Object encode() {
    return _toList();  }

  static ConnectionPlatformConfig decode(Object result) {
    result as List<Object?>;
    return ConnectionPlatformConfig(
      apple: result[0] as AppleConnectionOptions?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConnectionPlatformConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(apple, other.apple);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class BleConnectionParametersUpdated {
  BleConnectionParametersUpdated({
    required this.mtu,
    required this.deviceId,
    this.interval,
    this.latency,
    this.supervisionTimeout,
    this.status,
  });

  int mtu;

  String deviceId;

  int? interval;

  int? latency;

  int? supervisionTimeout;

  int? status;

  List<Object?> _toList() {
    return <Object?>[
      mtu,
      deviceId,
      interval,
      latency,
      supervisionTimeout,
      status,
    ];
  }

  Object encode() {
    return _toList();  }

  static BleConnectionParametersUpdated decode(Object result) {
    result as List<Object?>;
    return BleConnectionParametersUpdated(
      mtu: result[0]! as int,
      deviceId: result[1]! as String,
      interval: result[2] as int?,
      latency: result[3] as int?,
      supervisionTimeout: result[4] as int?,
      status: result[5] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BleConnectionParametersUpdated || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(mtu, other.mtu) && _deepEquals(deviceId, other.deviceId) && _deepEquals(interval, other.interval) && _deepEquals(latency, other.latency) && _deepEquals(supervisionTimeout, other.supervisionTimeout) && _deepEquals(status, other.status);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is BleLogLevel) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is AvailabilityState) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is BleConnectionState) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is BleInputProperty) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is BleOutputProperty) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is BleConnectionPriority) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is AndroidScanMode) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    }    else if (value is AndroidScanCallbackType) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    }    else if (value is AndroidScanMatchMode) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    }    else if (value is AndroidScanNumOfMatches) {
      buffer.putUint8(138);
      writeValue(buffer, value.index);
    }    else if (value is CharacteristicProperty) {
      buffer.putUint8(139);
      writeValue(buffer, value.index);
    }    else if (value is UniversalBleScanResult) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is UniversalManufacturerData) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is UniversalBleService) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is UniversalBleCharacteristic) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is UniversalBleDescriptor) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidOptions) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    }    else if (value is UniversalScanConfig) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    }    else if (value is UniversalScanFilter) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    }    else if (value is ManufacturerDataFilter) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    }    else if (value is AppleConnectionOptions) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    }    else if (value is ConnectionPlatformConfig) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    }    else if (value is BleConnectionParametersUpdated) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : BleLogLevel.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : AvailabilityState.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : BleConnectionState.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : BleInputProperty.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : BleOutputProperty.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : BleConnectionPriority.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidScanMode.values[value];
      case 136:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidScanCallbackType.values[value];
      case 137:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidScanMatchMode.values[value];
      case 138:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidScanNumOfMatches.values[value];
      case 139:
        final value = readValue(buffer) as int?;
        return value == null ? null : CharacteristicProperty.values[value];
      case 140:
        return UniversalBleScanResult.decode(readValue(buffer)!);
      case 141:
        return UniversalManufacturerData.decode(readValue(buffer)!);
      case 142:
        return UniversalBleService.decode(readValue(buffer)!);
      case 143:
        return UniversalBleCharacteristic.decode(readValue(buffer)!);
      case 144:
        return UniversalBleDescriptor.decode(readValue(buffer)!);
      case 145:
        return AndroidOptions.decode(readValue(buffer)!);
      case 146:
        return UniversalScanConfig.decode(readValue(buffer)!);
      case 147:
        return UniversalScanFilter.decode(readValue(buffer)!);
      case 148:
        return ManufacturerDataFilter.decode(readValue(buffer)!);
      case 149:
        return AppleConnectionOptions.decode(readValue(buffer)!);
      case 150:
        return ConnectionPlatformConfig.decode(readValue(buffer)!);
      case 151:
        return BleConnectionParametersUpdated.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class UniversalBlePlatformChannel {
  /// Constructor for [UniversalBlePlatformChannel].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  UniversalBlePlatformChannel({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<AvailabilityState> getBluetoothAvailabilityState() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.getBluetoothAvailabilityState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AvailabilityState;
  }

  Future<bool> hasPermissions() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.hasPermissions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> requestPermissions() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.requestPermissions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> enableBluetooth() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.enableBluetooth$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> disableBluetooth() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.disableBluetooth$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> startScan(List<UniversalScanFilter> filters, AndroidOptions androidOptions) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.startScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[filters, androidOptions]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stopScan() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.stopScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<bool> isScanning() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.isScanning$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> connect(String peripheralId, ConnectionPlatformConfig config) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.connect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[peripheralId, config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> disconnect(String peripheralId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.disconnect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[peripheralId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setNotifiable(String peripheralId, String serviceId, String characteristicId, BleInputProperty value) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.setNotifiable$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[peripheralId, serviceId, characteristicId, value]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<List<UniversalBleService>> discoverServices(String peripheralId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.discoverServices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[peripheralId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<UniversalBleService>();
  }

  Future<UniversalBleCharacteristic> readValue(String peripheralId, String serviceId, String characteristicId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.readValue$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[peripheralId, serviceId, characteristicId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as UniversalBleCharacteristic;
  }

  Future<int> requestMtu(String peripheralId, int mtu) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.requestMtu$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[peripheralId, mtu]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  Future<void> writeValue(String peripheralId, String serviceId, String characteristicId, List<int> value, BleOutputProperty bleOutputProperty) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.writeValue$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[peripheralId, serviceId, characteristicId, value, bleOutputProperty]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<bool> isPaired(String peripheralId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.isPaired$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[peripheralId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> pair(String peripheralId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.pair$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[peripheralId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> unPair(String peripheralId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.unPair$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[peripheralId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<List<UniversalBleScanResult>> getSystemDevices({List<String>? withServices}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.getSystemDevices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[withServices]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<UniversalBleScanResult>();
  }

  Future<BleConnectionState> getConnectionState(String peripheralId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.getConnectionState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[peripheralId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as BleConnectionState;
  }

  Future<int> readRssi(String peripheralId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.readRssi$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[peripheralId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  Future<void> requestConnectionPriority(String peripheralId, BleConnectionPriority priority) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.requestConnectionPriority$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[peripheralId, priority]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setLogLevel(BleLogLevel level) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.setLogLevel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[level]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class UniversalBleCallbackChannel {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onAvailabilityChanged(AvailabilityState state);

  void onPairStateChange(String peripheralId, bool isPaired);

  void onScanResult(UniversalBleScanResult result);

  void onValueChanged(String peripheralId, String serviceId, String characteristicId, List<int> value);

  void onConnectionChanged(String peripheralId, BleConnectionState state);

  void onConnectionParametersUpdated(BleConnectionParametersUpdated result);

  static void setUp(UniversalBleCallbackChannel? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onAvailabilityChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AvailabilityState arg_state = args[0]! as AvailabilityState;
          try {
            api.onAvailabilityChanged(arg_state);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onPairStateChange$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_peripheralId = args[0]! as String;
          final bool arg_isPaired = args[1]! as bool;
          try {
            api.onPairStateChange(arg_peripheralId, arg_isPaired);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onScanResult$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final UniversalBleScanResult arg_result = args[0]! as UniversalBleScanResult;
          try {
            api.onScanResult(arg_result);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onValueChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_peripheralId = args[0]! as String;
          final String arg_serviceId = args[1]! as String;
          final String arg_characteristicId = args[2]! as String;
          final List<int> arg_value = (args[3]! as List<Object?>).cast<int>();
          try {
            api.onValueChanged(arg_peripheralId, arg_serviceId, arg_characteristicId, arg_value);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onConnectionChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_peripheralId = args[0]! as String;
          final BleConnectionState arg_state = args[1]! as BleConnectionState;
          try {
            api.onConnectionChanged(arg_peripheralId, arg_state);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onConnectionParametersUpdated$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final BleConnectionParametersUpdated arg_result = args[0]! as BleConnectionParametersUpdated;
          try {
            api.onConnectionParametersUpdated(arg_result);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
