// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.printer_connect

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PrinterConnectPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class BleLogLevel(val raw: Int) {
  NONE(0),
  ERROR(1),
  WARNING(2),
  INFO(3),
  DEBUG(4),
  VERBOSE(5);

  companion object {
    fun ofRaw(raw: Int): BleLogLevel? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class AvailabilityState(val raw: Int) {
  UNKNOWN(0),
  RESETTING(1),
  UNSUPPORTED(2),
  UNAUTHORIZED(3),
  POWERED_OFF(4),
  POWERED_ON(5);

  companion object {
    fun ofRaw(raw: Int): AvailabilityState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BleConnectionState(val raw: Int) {
  CONNECTED(0),
  DISCONNECTED(1),
  CONNECTING(2),
  DISCONNECTING(3);

  companion object {
    fun ofRaw(raw: Int): BleConnectionState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BleInputProperty(val raw: Int) {
  DISABLED(0),
  NOTIFICATION(1),
  INDICATION(2);

  companion object {
    fun ofRaw(raw: Int): BleInputProperty? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BleOutputProperty(val raw: Int) {
  WITH_RESPONSE(0),
  WITHOUT_RESPONSE(1);

  companion object {
    fun ofRaw(raw: Int): BleOutputProperty? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BleConnectionPriority(val raw: Int) {
  BALANCED(0),
  HIGH_PERFORMANCE(1),
  LOW_POWER(2);

  companion object {
    fun ofRaw(raw: Int): BleConnectionPriority? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class AndroidScanMode(val raw: Int) {
  BALANCED(0),
  LOW_LATENCY(1),
  LOW_POWER(2),
  OPPORTUNISTIC(3);

  companion object {
    fun ofRaw(raw: Int): AndroidScanMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class AndroidScanCallbackType(val raw: Int) {
  ALL_MATCHES(0),
  FIRST_MATCH(1),
  MATCH_LOST(2),
  ALL_MATCHES_AUTO_BATCH(3);

  companion object {
    fun ofRaw(raw: Int): AndroidScanCallbackType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class AndroidScanMatchMode(val raw: Int) {
  AGGRESSIVE(0),
  STICKY(1);

  companion object {
    fun ofRaw(raw: Int): AndroidScanMatchMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class AndroidScanNumOfMatches(val raw: Int) {
  ONE(0),
  FEW(1),
  MAX(2);

  companion object {
    fun ofRaw(raw: Int): AndroidScanNumOfMatches? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CharacteristicProperty(val raw: Int) {
  BROADCAST(0),
  READ(1),
  WRITE_WITHOUT_RESPONSE(2),
  WRITE(3),
  NOTIFY(4),
  INDICATE(5),
  AUTHENTICATED_SIGNED_WRITES(6),
  EXTENDED_PROPERTIES(7);

  companion object {
    fun ofRaw(raw: Int): CharacteristicProperty? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UniversalBleScanResult (
  val deviceId: String,
  val name: String? = null,
  val rssi: Long? = null,
  val manufacturerDataList: List<UniversalManufacturerData>? = null,
  val serviceData: Map<String, ByteArray>? = null,
  val services: List<String>? = null,
  val timestamp: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UniversalBleScanResult {
      val deviceId = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String?
      val rssi = pigeonVar_list[2] as Long?
      val manufacturerDataList = pigeonVar_list[3] as List<UniversalManufacturerData>?
      val serviceData = pigeonVar_list[4] as Map<String, ByteArray>?
      val services = pigeonVar_list[5] as List<String>?
      val timestamp = pigeonVar_list[6] as Long?
      return UniversalBleScanResult(deviceId, name, rssi, manufacturerDataList, serviceData, services, timestamp)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      deviceId,
      name,
      rssi,
      manufacturerDataList,
      serviceData,
      services,
      timestamp,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UniversalBleScanResult
    return PrinterConnectPigeonUtils.deepEquals(this.deviceId, other.deviceId) && PrinterConnectPigeonUtils.deepEquals(this.name, other.name) && PrinterConnectPigeonUtils.deepEquals(this.rssi, other.rssi) && PrinterConnectPigeonUtils.deepEquals(this.manufacturerDataList, other.manufacturerDataList) && PrinterConnectPigeonUtils.deepEquals(this.serviceData, other.serviceData) && PrinterConnectPigeonUtils.deepEquals(this.services, other.services) && PrinterConnectPigeonUtils.deepEquals(this.timestamp, other.timestamp)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.name)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.rssi)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.manufacturerDataList)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.serviceData)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.services)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.timestamp)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UniversalBleService (
  val uuid: String,
  val characteristics: List<UniversalBleCharacteristic>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UniversalBleService {
      val uuid = pigeonVar_list[0] as String
      val characteristics = pigeonVar_list[1] as List<UniversalBleCharacteristic>?
      return UniversalBleService(uuid, characteristics)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      characteristics,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UniversalBleService
    return PrinterConnectPigeonUtils.deepEquals(this.uuid, other.uuid) && PrinterConnectPigeonUtils.deepEquals(this.characteristics, other.characteristics)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.uuid)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.characteristics)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UniversalBleCharacteristic (
  val uuid: String,
  val properties: List<CharacteristicProperty>,
  val descriptors: List<UniversalBleDescriptor>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UniversalBleCharacteristic {
      val uuid = pigeonVar_list[0] as String
      val properties = pigeonVar_list[1] as List<CharacteristicProperty>
      val descriptors = pigeonVar_list[2] as List<UniversalBleDescriptor>
      return UniversalBleCharacteristic(uuid, properties, descriptors)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      properties,
      descriptors,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UniversalBleCharacteristic
    return PrinterConnectPigeonUtils.deepEquals(this.uuid, other.uuid) && PrinterConnectPigeonUtils.deepEquals(this.properties, other.properties) && PrinterConnectPigeonUtils.deepEquals(this.descriptors, other.descriptors)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.uuid)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.properties)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.descriptors)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UniversalBleDescriptor (
  val uuid: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UniversalBleDescriptor {
      val uuid = pigeonVar_list[0] as String
      return UniversalBleDescriptor(uuid)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UniversalBleDescriptor
    return PrinterConnectPigeonUtils.deepEquals(this.uuid, other.uuid)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.uuid)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleConnectionParametersUpdated (
  val deviceId: String,
  val interval: Long,
  val latency: Long,
  val supervisionTimeout: Long,
  val status: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleConnectionParametersUpdated {
      val deviceId = pigeonVar_list[0] as String
      val interval = pigeonVar_list[1] as Long
      val latency = pigeonVar_list[2] as Long
      val supervisionTimeout = pigeonVar_list[3] as Long
      val status = pigeonVar_list[4] as Long
      return BleConnectionParametersUpdated(deviceId, interval, latency, supervisionTimeout, status)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      deviceId,
      interval,
      latency,
      supervisionTimeout,
      status,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleConnectionParametersUpdated
    return PrinterConnectPigeonUtils.deepEquals(this.deviceId, other.deviceId) && PrinterConnectPigeonUtils.deepEquals(this.interval, other.interval) && PrinterConnectPigeonUtils.deepEquals(this.latency, other.latency) && PrinterConnectPigeonUtils.deepEquals(this.supervisionTimeout, other.supervisionTimeout) && PrinterConnectPigeonUtils.deepEquals(this.status, other.status)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.interval)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.latency)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.supervisionTimeout)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.status)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AndroidOptions (
  val requestLocationPermission: Boolean? = null,
  val scanMode: AndroidScanMode? = null,
  val reportDelayMillis: Long? = null,
  val callbackType: List<AndroidScanCallbackType>? = null,
  val matchMode: AndroidScanMatchMode? = null,
  val numOfMatches: AndroidScanNumOfMatches? = null,
  val legacy: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidOptions {
      val requestLocationPermission = pigeonVar_list[0] as Boolean?
      val scanMode = pigeonVar_list[1] as AndroidScanMode?
      val reportDelayMillis = pigeonVar_list[2] as Long?
      val callbackType = pigeonVar_list[3] as List<AndroidScanCallbackType>?
      val matchMode = pigeonVar_list[4] as AndroidScanMatchMode?
      val numOfMatches = pigeonVar_list[5] as AndroidScanNumOfMatches?
      val legacy = pigeonVar_list[6] as Boolean?
      return AndroidOptions(requestLocationPermission, scanMode, reportDelayMillis, callbackType, matchMode, numOfMatches, legacy)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestLocationPermission,
      scanMode,
      reportDelayMillis,
      callbackType,
      matchMode,
      numOfMatches,
      legacy,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AndroidOptions
    return PrinterConnectPigeonUtils.deepEquals(this.requestLocationPermission, other.requestLocationPermission) && PrinterConnectPigeonUtils.deepEquals(this.scanMode, other.scanMode) && PrinterConnectPigeonUtils.deepEquals(this.reportDelayMillis, other.reportDelayMillis) && PrinterConnectPigeonUtils.deepEquals(this.callbackType, other.callbackType) && PrinterConnectPigeonUtils.deepEquals(this.matchMode, other.matchMode) && PrinterConnectPigeonUtils.deepEquals(this.numOfMatches, other.numOfMatches) && PrinterConnectPigeonUtils.deepEquals(this.legacy, other.legacy)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.requestLocationPermission)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.scanMode)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.reportDelayMillis)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.callbackType)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.matchMode)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.numOfMatches)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.legacy)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UniversalScanConfig (
  val android: AndroidOptions? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UniversalScanConfig {
      val android = pigeonVar_list[0] as AndroidOptions?
      return UniversalScanConfig(android)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      android,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UniversalScanConfig
    return PrinterConnectPigeonUtils.deepEquals(this.android, other.android)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.android)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UniversalScanFilter (
  val withServices: List<String>,
  val withNamePrefix: List<String>,
  val withManufacturerData: List<ManufacturerDataFilter>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UniversalScanFilter {
      val withServices = pigeonVar_list[0] as List<String>
      val withNamePrefix = pigeonVar_list[1] as List<String>
      val withManufacturerData = pigeonVar_list[2] as List<ManufacturerDataFilter>
      return UniversalScanFilter(withServices, withNamePrefix, withManufacturerData)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      withServices,
      withNamePrefix,
      withManufacturerData,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UniversalScanFilter
    return PrinterConnectPigeonUtils.deepEquals(this.withServices, other.withServices) && PrinterConnectPigeonUtils.deepEquals(this.withNamePrefix, other.withNamePrefix) && PrinterConnectPigeonUtils.deepEquals(this.withManufacturerData, other.withManufacturerData)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.withServices)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.withNamePrefix)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.withManufacturerData)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ManufacturerDataFilter (
  val companyIdentifier: Long,
  val payloadPrefix: ByteArray? = null,
  val payloadMask: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ManufacturerDataFilter {
      val companyIdentifier = pigeonVar_list[0] as Long
      val payloadPrefix = pigeonVar_list[1] as ByteArray?
      val payloadMask = pigeonVar_list[2] as ByteArray?
      return ManufacturerDataFilter(companyIdentifier, payloadPrefix, payloadMask)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      companyIdentifier,
      payloadPrefix,
      payloadMask,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ManufacturerDataFilter
    return PrinterConnectPigeonUtils.deepEquals(this.companyIdentifier, other.companyIdentifier) && PrinterConnectPigeonUtils.deepEquals(this.payloadPrefix, other.payloadPrefix) && PrinterConnectPigeonUtils.deepEquals(this.payloadMask, other.payloadMask)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.companyIdentifier)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.payloadPrefix)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.payloadMask)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UniversalManufacturerData (
  val companyIdentifier: Long,
  val data: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UniversalManufacturerData {
      val companyIdentifier = pigeonVar_list[0] as Long
      val data = pigeonVar_list[1] as ByteArray
      return UniversalManufacturerData(companyIdentifier, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      companyIdentifier,
      data,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UniversalManufacturerData
    return PrinterConnectPigeonUtils.deepEquals(this.companyIdentifier, other.companyIdentifier) && PrinterConnectPigeonUtils.deepEquals(this.data, other.data)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.companyIdentifier)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.data)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AppleConnectionOptions (
  val notifyOnConnection: Boolean? = null,
  val notifyOnDisconnection: Boolean? = null,
  val notifyOnNotification: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AppleConnectionOptions {
      val notifyOnConnection = pigeonVar_list[0] as Boolean?
      val notifyOnDisconnection = pigeonVar_list[1] as Boolean?
      val notifyOnNotification = pigeonVar_list[2] as Boolean?
      return AppleConnectionOptions(notifyOnConnection, notifyOnDisconnection, notifyOnNotification)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      notifyOnConnection,
      notifyOnDisconnection,
      notifyOnNotification,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AppleConnectionOptions
    return PrinterConnectPigeonUtils.deepEquals(this.notifyOnConnection, other.notifyOnConnection) && PrinterConnectPigeonUtils.deepEquals(this.notifyOnDisconnection, other.notifyOnDisconnection) && PrinterConnectPigeonUtils.deepEquals(this.notifyOnNotification, other.notifyOnNotification)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.notifyOnConnection)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.notifyOnDisconnection)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.notifyOnNotification)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConnectionPlatformConfig (
  val apple: AppleConnectionOptions? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConnectionPlatformConfig {
      val apple = pigeonVar_list[0] as AppleConnectionOptions?
      return ConnectionPlatformConfig(apple)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      apple,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConnectionPlatformConfig
    return PrinterConnectPigeonUtils.deepEquals(this.apple, other.apple)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.apple)
    return result
  }
}
private open class PrinterConnectPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BleLogLevel.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AvailabilityState.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BleConnectionState.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BleInputProperty.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BleOutputProperty.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BleConnectionPriority.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AndroidScanMode.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AndroidScanCallbackType.ofRaw(it.toInt())
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AndroidScanMatchMode.ofRaw(it.toInt())
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AndroidScanNumOfMatches.ofRaw(it.toInt())
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CharacteristicProperty.ofRaw(it.toInt())
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UniversalBleScanResult.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UniversalBleService.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UniversalBleCharacteristic.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UniversalBleDescriptor.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleConnectionParametersUpdated.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidOptions.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UniversalScanConfig.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UniversalScanFilter.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ManufacturerDataFilter.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UniversalManufacturerData.fromList(it)
        }
      }
      150.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AppleConnectionOptions.fromList(it)
        }
      }
      151.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConnectionPlatformConfig.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BleLogLevel -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is AvailabilityState -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is BleConnectionState -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is BleInputProperty -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is BleOutputProperty -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is BleConnectionPriority -> {
        stream.write(134)
        writeValue(stream, value.raw.toLong())
      }
      is AndroidScanMode -> {
        stream.write(135)
        writeValue(stream, value.raw.toLong())
      }
      is AndroidScanCallbackType -> {
        stream.write(136)
        writeValue(stream, value.raw.toLong())
      }
      is AndroidScanMatchMode -> {
        stream.write(137)
        writeValue(stream, value.raw.toLong())
      }
      is AndroidScanNumOfMatches -> {
        stream.write(138)
        writeValue(stream, value.raw.toLong())
      }
      is CharacteristicProperty -> {
        stream.write(139)
        writeValue(stream, value.raw.toLong())
      }
      is UniversalBleScanResult -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is UniversalBleService -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is UniversalBleCharacteristic -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is UniversalBleDescriptor -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is BleConnectionParametersUpdated -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is AndroidOptions -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is UniversalScanConfig -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is UniversalScanFilter -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is ManufacturerDataFilter -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is UniversalManufacturerData -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      is AppleConnectionOptions -> {
        stream.write(150)
        writeValue(stream, value.toList())
      }
      is ConnectionPlatformConfig -> {
        stream.write(151)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface UniversalBlePlatformChannel {
  fun getBluetoothAvailabilityState(callback: (Result<AvailabilityState>) -> Unit)
  fun hasPermissions(withAndroidFineLocation: Boolean): Boolean
  fun requestPermissions(withAndroidFineLocation: Boolean, callback: (Result<Unit>) -> Unit)
  fun enableBluetooth(callback: (Result<Boolean>) -> Unit)
  fun startScan(filter: UniversalScanFilter?, config: UniversalScanConfig?)
  fun stopScan()
  fun isScanning(): Boolean
  fun connect(deviceId: String, autoConnect: Boolean?, platformConfig: ConnectionPlatformConfig?)
  fun disconnect(deviceId: String)
  fun setNotifiable(deviceId: String, service: String, characteristic: String, bleInputProperty: BleInputProperty, callback: (Result<Unit>) -> Unit)
  fun discoverServices(deviceId: String, withDescriptors: Boolean, callback: (Result<List<UniversalBleService>>) -> Unit)
  fun readValue(deviceId: String, service: String, characteristic: String, callback: (Result<ByteArray>) -> Unit)
  fun requestMtu(deviceId: String, expectedMtu: Long, callback: (Result<Long>) -> Unit)
  fun writeValue(deviceId: String, service: String, characteristic: String, value: ByteArray, bleOutputProperty: BleOutputProperty, callback: (Result<Unit>) -> Unit)
  fun getSystemDevices(withServices: List<String>, callback: (Result<List<UniversalBleScanResult>>) -> Unit)
  fun getConnectionState(deviceId: String): BleConnectionState
  fun readRssi(deviceId: String, callback: (Result<Long>) -> Unit)
  fun requestConnectionPriority(deviceId: String, priority: BleConnectionPriority, callback: (Result<Unit>) -> Unit)
  fun setLogLevel(logLevel: BleLogLevel)

  companion object {
    /** The codec used by UniversalBlePlatformChannel. */
    val codec: MessageCodec<Any?> by lazy {
      PrinterConnectPigeonCodec()
    }
    /** Sets up an instance of `UniversalBlePlatformChannel` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: UniversalBlePlatformChannel?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.getBluetoothAvailabilityState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getBluetoothAvailabilityState{ result: Result<AvailabilityState> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrinterConnectPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.hasPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val withAndroidFineLocationArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              listOf(api.hasPermissions(withAndroidFineLocationArg))
            } catch (exception: Throwable) {
              PrinterConnectPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.requestPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val withAndroidFineLocationArg = args[0] as Boolean
            api.requestPermissions(withAndroidFineLocationArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                reply.reply(PrinterConnectPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.enableBluetooth$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.enableBluetooth{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrinterConnectPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.startScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filterArg = args[0] as UniversalScanFilter?
            val configArg = args[1] as UniversalScanConfig?
            val wrapped: List<Any?> = try {
              api.startScan(filterArg, configArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrinterConnectPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.stopScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopScan()
              listOf(null)
            } catch (exception: Throwable) {
              PrinterConnectPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.isScanning$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isScanning())
            } catch (exception: Throwable) {
              PrinterConnectPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val autoConnectArg = args[1] as Boolean?
            val platformConfigArg = args[2] as ConnectionPlatformConfig?
            val wrapped: List<Any?> = try {
              api.connect(deviceIdArg, autoConnectArg, platformConfigArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrinterConnectPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.disconnect(deviceIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrinterConnectPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.setNotifiable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val serviceArg = args[1] as String
            val characteristicArg = args[2] as String
            val bleInputPropertyArg = args[3] as BleInputProperty
            api.setNotifiable(deviceIdArg, serviceArg, characteristicArg, bleInputPropertyArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                reply.reply(PrinterConnectPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.discoverServices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val withDescriptorsArg = args[1] as Boolean
            api.discoverServices(deviceIdArg, withDescriptorsArg) { result: Result<List<UniversalBleService>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrinterConnectPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.readValue$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val serviceArg = args[1] as String
            val characteristicArg = args[2] as String
            api.readValue(deviceIdArg, serviceArg, characteristicArg) { result: Result<ByteArray> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrinterConnectPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.requestMtu$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val expectedMtuArg = args[1] as Long
            api.requestMtu(deviceIdArg, expectedMtuArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrinterConnectPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.writeValue$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val serviceArg = args[1] as String
            val characteristicArg = args[2] as String
            val valueArg = args[3] as ByteArray
            val bleOutputPropertyArg = args[4] as BleOutputProperty
            api.writeValue(deviceIdArg, serviceArg, characteristicArg, valueArg, bleOutputPropertyArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                reply.reply(PrinterConnectPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.getSystemDevices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val withServicesArg = args[0] as List<String>
            api.getSystemDevices(withServicesArg) { result: Result<List<UniversalBleScanResult>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrinterConnectPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.getConnectionState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.getConnectionState(deviceIdArg))
            } catch (exception: Throwable) {
              PrinterConnectPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.readRssi$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            api.readRssi(deviceIdArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrinterConnectPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.requestConnectionPriority$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val priorityArg = args[1] as BleConnectionPriority
            api.requestConnectionPriority(deviceIdArg, priorityArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                reply.reply(PrinterConnectPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.setLogLevel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val logLevelArg = args[0] as BleLogLevel
            val wrapped: List<Any?> = try {
              api.setLogLevel(logLevelArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrinterConnectPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class UniversalBleCallbackChannel(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by UniversalBleCallbackChannel. */
    val codec: MessageCodec<Any?> by lazy {
      PrinterConnectPigeonCodec()
    }
  }
  fun onAvailabilityChanged(stateArg: AvailabilityState, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onAvailabilityChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PrinterConnectPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onScanResult(resultArg: UniversalBleScanResult, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onScanResult$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(resultArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PrinterConnectPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onValueChanged(deviceIdArg: String, characteristicIdArg: String, valueArg: ByteArray, timestampArg: Long?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onValueChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg, characteristicIdArg, valueArg, timestampArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PrinterConnectPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onConnectionChanged(deviceIdArg: String, connectedArg: Boolean, errorArg: String?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onConnectionChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg, connectedArg, errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PrinterConnectPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onConnectionParametersUpdated(updateArg: BleConnectionParametersUpdated, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onConnectionParametersUpdated$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(updateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PrinterConnectPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
