// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.printer_connect

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PrinterConnectPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class BleLogLevel(val raw: Int) {
  VERBOSE(0),
  DEBUG(1),
  INFO(2),
  WARNING(3),
  ERROR(4),
  WTF(5),
  NONE(6);

  companion object {
    fun ofRaw(raw: Int): BleLogLevel? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class AvailabilityState(val raw: Int) {
  UNKNOWN(0),
  RESETTING(1),
  UNSUPPORTED(2),
  UNAUTHORIZED(3),
  POWERED_OFF(4),
  POWERED_ON(5);

  companion object {
    fun ofRaw(raw: Int): AvailabilityState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BleConnectionState(val raw: Int) {
  DISCONNECTED(0),
  CONNECTING(1),
  CONNECTED(2),
  DISCONNECTING(3);

  companion object {
    fun ofRaw(raw: Int): BleConnectionState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BleInputProperty(val raw: Int) {
  DISABLED(0),
  NOTIFICATION(1),
  INDICATION(2);

  companion object {
    fun ofRaw(raw: Int): BleInputProperty? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BleOutputProperty(val raw: Int) {
  NONE(0),
  WRITE(1),
  WRITE_WITHOUT_RESPONSE(2);

  companion object {
    fun ofRaw(raw: Int): BleOutputProperty? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BleConnectionPriority(val raw: Int) {
  BALANCED(0),
  HIGH_PERFORMANCE(1),
  LOW_POWER(2);

  companion object {
    fun ofRaw(raw: Int): BleConnectionPriority? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class AndroidScanMode(val raw: Int) {
  LOW_POWERED(0),
  BALANCED(1),
  LOW_LATENCY(2);

  companion object {
    fun ofRaw(raw: Int): AndroidScanMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class AndroidScanCallbackType(val raw: Int) {
  DEFAULT_(0),
  FIRST_MATCH(1),
  LOSE(2),
  MATCHED(3);

  companion object {
    fun ofRaw(raw: Int): AndroidScanCallbackType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class AndroidScanMatchMode(val raw: Int) {
  DEFAULT_(0),
  STICKY(1);

  companion object {
    fun ofRaw(raw: Int): AndroidScanMatchMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class AndroidScanNumOfMatches(val raw: Int) {
  ONE(0),
  FEW(1),
  MANY(2);

  companion object {
    fun ofRaw(raw: Int): AndroidScanNumOfMatches? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CharacteristicProperty(val raw: Int) {
  READ(0),
  WRITE(1),
  WRITE_WITHOUT_RESPONSE(2),
  NOTIFY(3),
  INDICATE(4),
  BROADCAST(5),
  EXTENDED_SBLE_PROPS(6),
  SIGNED_WRITE(7);

  companion object {
    fun ofRaw(raw: Int): CharacteristicProperty? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UniversalBleScanResult (
  val peripheralId: String,
  val name: String? = null,
  val rssi: Long,
  val manufacturerData: List<UniversalManufacturerData>? = null,
  val serviceData: List<Long>? = null,
  val serviceUuids: List<String>? = null,
  val txPowerLevel: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UniversalBleScanResult {
      val peripheralId = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String?
      val rssi = pigeonVar_list[2] as Long
      val manufacturerData = pigeonVar_list[3] as List<UniversalManufacturerData>?
      val serviceData = pigeonVar_list[4] as List<Long>?
      val serviceUuids = pigeonVar_list[5] as List<String>?
      val txPowerLevel = pigeonVar_list[6] as Long?
      return UniversalBleScanResult(peripheralId, name, rssi, manufacturerData, serviceData, serviceUuids, txPowerLevel)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      peripheralId,
      name,
      rssi,
      manufacturerData,
      serviceData,
      serviceUuids,
      txPowerLevel,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UniversalBleScanResult
    return PrinterConnectPigeonUtils.deepEquals(this.peripheralId, other.peripheralId) && PrinterConnectPigeonUtils.deepEquals(this.name, other.name) && PrinterConnectPigeonUtils.deepEquals(this.rssi, other.rssi) && PrinterConnectPigeonUtils.deepEquals(this.manufacturerData, other.manufacturerData) && PrinterConnectPigeonUtils.deepEquals(this.serviceData, other.serviceData) && PrinterConnectPigeonUtils.deepEquals(this.serviceUuids, other.serviceUuids) && PrinterConnectPigeonUtils.deepEquals(this.txPowerLevel, other.txPowerLevel)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.peripheralId)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.name)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.rssi)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.manufacturerData)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.serviceData)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.serviceUuids)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.txPowerLevel)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UniversalManufacturerData (
  val id: Long,
  val data: List<Long>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UniversalManufacturerData {
      val id = pigeonVar_list[0] as Long
      val data = pigeonVar_list[1] as List<Long>
      return UniversalManufacturerData(id, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      data,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UniversalManufacturerData
    return PrinterConnectPigeonUtils.deepEquals(this.id, other.id) && PrinterConnectPigeonUtils.deepEquals(this.data, other.data)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.id)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.data)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UniversalBleService (
  val uuid: String,
  val isPrimary: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UniversalBleService {
      val uuid = pigeonVar_list[0] as String
      val isPrimary = pigeonVar_list[1] as Boolean
      return UniversalBleService(uuid, isPrimary)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      isPrimary,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UniversalBleService
    return PrinterConnectPigeonUtils.deepEquals(this.uuid, other.uuid) && PrinterConnectPigeonUtils.deepEquals(this.isPrimary, other.isPrimary)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.uuid)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.isPrimary)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UniversalBleCharacteristic (
  val uuid: String,
  val properties: List<CharacteristicProperty>,
  val value: List<Long>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UniversalBleCharacteristic {
      val uuid = pigeonVar_list[0] as String
      val properties = pigeonVar_list[1] as List<CharacteristicProperty>
      val value = pigeonVar_list[2] as List<Long>?
      return UniversalBleCharacteristic(uuid, properties, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      properties,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UniversalBleCharacteristic
    return PrinterConnectPigeonUtils.deepEquals(this.uuid, other.uuid) && PrinterConnectPigeonUtils.deepEquals(this.properties, other.properties) && PrinterConnectPigeonUtils.deepEquals(this.value, other.value)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.uuid)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.properties)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.value)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UniversalBleDescriptor (
  val uuid: String,
  val value: List<Long>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UniversalBleDescriptor {
      val uuid = pigeonVar_list[0] as String
      val value = pigeonVar_list[1] as List<Long>?
      return UniversalBleDescriptor(uuid, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UniversalBleDescriptor
    return PrinterConnectPigeonUtils.deepEquals(this.uuid, other.uuid) && PrinterConnectPigeonUtils.deepEquals(this.value, other.value)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.uuid)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.value)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AndroidOptions (
  val scanMode: AndroidScanMode? = null,
  val callbackType: AndroidScanCallbackType? = null,
  val matchMode: AndroidScanMatchMode? = null,
  val numOfMatches: AndroidScanNumOfMatches? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidOptions {
      val scanMode = pigeonVar_list[0] as AndroidScanMode?
      val callbackType = pigeonVar_list[1] as AndroidScanCallbackType?
      val matchMode = pigeonVar_list[2] as AndroidScanMatchMode?
      val numOfMatches = pigeonVar_list[3] as AndroidScanNumOfMatches?
      return AndroidOptions(scanMode, callbackType, matchMode, numOfMatches)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      scanMode,
      callbackType,
      matchMode,
      numOfMatches,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AndroidOptions
    return PrinterConnectPigeonUtils.deepEquals(this.scanMode, other.scanMode) && PrinterConnectPigeonUtils.deepEquals(this.callbackType, other.callbackType) && PrinterConnectPigeonUtils.deepEquals(this.matchMode, other.matchMode) && PrinterConnectPigeonUtils.deepEquals(this.numOfMatches, other.numOfMatches)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.scanMode)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.callbackType)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.matchMode)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.numOfMatches)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UniversalScanConfig (
  val scanFilters: List<UniversalScanFilter>? = null,
  val androidOptions: AndroidOptions? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UniversalScanConfig {
      val scanFilters = pigeonVar_list[0] as List<UniversalScanFilter>?
      val androidOptions = pigeonVar_list[1] as AndroidOptions?
      return UniversalScanConfig(scanFilters, androidOptions)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      scanFilters,
      androidOptions,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UniversalScanConfig
    return PrinterConnectPigeonUtils.deepEquals(this.scanFilters, other.scanFilters) && PrinterConnectPigeonUtils.deepEquals(this.androidOptions, other.androidOptions)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.scanFilters)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.androidOptions)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UniversalScanFilter (
  val withServices: List<String>? = null,
  val withManufacturerData: List<ManufacturerDataFilter>? = null,
  val withLocalName: String? = null,
  val withLocalNamePrefix: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UniversalScanFilter {
      val withServices = pigeonVar_list[0] as List<String>?
      val withManufacturerData = pigeonVar_list[1] as List<ManufacturerDataFilter>?
      val withLocalName = pigeonVar_list[2] as String?
      val withLocalNamePrefix = pigeonVar_list[3] as String?
      return UniversalScanFilter(withServices, withManufacturerData, withLocalName, withLocalNamePrefix)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      withServices,
      withManufacturerData,
      withLocalName,
      withLocalNamePrefix,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UniversalScanFilter
    return PrinterConnectPigeonUtils.deepEquals(this.withServices, other.withServices) && PrinterConnectPigeonUtils.deepEquals(this.withManufacturerData, other.withManufacturerData) && PrinterConnectPigeonUtils.deepEquals(this.withLocalName, other.withLocalName) && PrinterConnectPigeonUtils.deepEquals(this.withLocalNamePrefix, other.withLocalNamePrefix)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.withServices)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.withManufacturerData)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.withLocalName)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.withLocalNamePrefix)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ManufacturerDataFilter (
  val companyId: Long,
  val data: List<Long>? = null,
  val mask: List<Long>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ManufacturerDataFilter {
      val companyId = pigeonVar_list[0] as Long
      val data = pigeonVar_list[1] as List<Long>?
      val mask = pigeonVar_list[2] as List<Long>?
      return ManufacturerDataFilter(companyId, data, mask)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      companyId,
      data,
      mask,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ManufacturerDataFilter
    return PrinterConnectPigeonUtils.deepEquals(this.companyId, other.companyId) && PrinterConnectPigeonUtils.deepEquals(this.data, other.data) && PrinterConnectPigeonUtils.deepEquals(this.mask, other.mask)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.companyId)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.data)
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.mask)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AppleConnectionOptions (
  val shouldRestoreState: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AppleConnectionOptions {
      val shouldRestoreState = pigeonVar_list[0] as Boolean?
      return AppleConnectionOptions(shouldRestoreState)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      shouldRestoreState,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AppleConnectionOptions
    return PrinterConnectPigeonUtils.deepEquals(this.shouldRestoreState, other.shouldRestoreState)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.shouldRestoreState)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConnectionPlatformConfig (
  val apple: AppleConnectionOptions? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConnectionPlatformConfig {
      val apple = pigeonVar_list[0] as AppleConnectionOptions?
      return ConnectionPlatformConfig(apple)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      apple,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConnectionPlatformConfig
    return PrinterConnectPigeonUtils.deepEquals(this.apple, other.apple)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.apple)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleConnectionParametersUpdated (
  val mtu: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleConnectionParametersUpdated {
      val mtu = pigeonVar_list[0] as Long
      return BleConnectionParametersUpdated(mtu)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mtu,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleConnectionParametersUpdated
    return PrinterConnectPigeonUtils.deepEquals(this.mtu, other.mtu)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrinterConnectPigeonUtils.deepHash(this.mtu)
    return result
  }
}
private open class PrinterConnectPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BleLogLevel.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AvailabilityState.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BleConnectionState.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BleInputProperty.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BleOutputProperty.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BleConnectionPriority.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AndroidScanMode.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AndroidScanCallbackType.ofRaw(it.toInt())
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AndroidScanMatchMode.ofRaw(it.toInt())
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AndroidScanNumOfMatches.ofRaw(it.toInt())
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CharacteristicProperty.ofRaw(it.toInt())
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UniversalBleScanResult.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UniversalManufacturerData.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UniversalBleService.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UniversalBleCharacteristic.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UniversalBleDescriptor.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidOptions.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UniversalScanConfig.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UniversalScanFilter.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ManufacturerDataFilter.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AppleConnectionOptions.fromList(it)
        }
      }
      150.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConnectionPlatformConfig.fromList(it)
        }
      }
      151.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleConnectionParametersUpdated.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BleLogLevel -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is AvailabilityState -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is BleConnectionState -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is BleInputProperty -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is BleOutputProperty -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is BleConnectionPriority -> {
        stream.write(134)
        writeValue(stream, value.raw.toLong())
      }
      is AndroidScanMode -> {
        stream.write(135)
        writeValue(stream, value.raw.toLong())
      }
      is AndroidScanCallbackType -> {
        stream.write(136)
        writeValue(stream, value.raw.toLong())
      }
      is AndroidScanMatchMode -> {
        stream.write(137)
        writeValue(stream, value.raw.toLong())
      }
      is AndroidScanNumOfMatches -> {
        stream.write(138)
        writeValue(stream, value.raw.toLong())
      }
      is CharacteristicProperty -> {
        stream.write(139)
        writeValue(stream, value.raw.toLong())
      }
      is UniversalBleScanResult -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is UniversalManufacturerData -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is UniversalBleService -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is UniversalBleCharacteristic -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is UniversalBleDescriptor -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is AndroidOptions -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is UniversalScanConfig -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is UniversalScanFilter -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is ManufacturerDataFilter -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is AppleConnectionOptions -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      is ConnectionPlatformConfig -> {
        stream.write(150)
        writeValue(stream, value.toList())
      }
      is BleConnectionParametersUpdated -> {
        stream.write(151)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface UniversalBlePlatformChannel {
  fun getBluetoothAvailabilityState(callback: (Result<AvailabilityState>) -> Unit)
  fun hasPermissions(callback: (Result<Boolean>) -> Unit)
  fun requestPermissions(callback: (Result<Boolean>) -> Unit)
  fun enableBluetooth(callback: (Result<Unit>) -> Unit)
  fun disableBluetooth(callback: (Result<Unit>) -> Unit)
  fun startScan(filters: List<UniversalScanFilter>, androidOptions: AndroidOptions, callback: (Result<Unit>) -> Unit)
  fun stopScan(callback: (Result<Unit>) -> Unit)
  fun isScanning(callback: (Result<Boolean>) -> Unit)
  fun connect(peripheralId: String, config: ConnectionPlatformConfig, callback: (Result<Unit>) -> Unit)
  fun disconnect(peripheralId: String, callback: (Result<Unit>) -> Unit)
  fun setNotifiable(peripheralId: String, serviceId: String, characteristicId: String, value: BleInputProperty, callback: (Result<Unit>) -> Unit)
  fun discoverServices(peripheralId: String, callback: (Result<List<UniversalBleService>>) -> Unit)
  fun readValue(peripheralId: String, serviceId: String, characteristicId: String, callback: (Result<UniversalBleCharacteristic>) -> Unit)
  fun requestMtu(peripheralId: String, mtu: Long, callback: (Result<Long>) -> Unit)
  fun writeValue(peripheralId: String, serviceId: String, characteristicId: String, value: List<Long>, bleOutputProperty: BleOutputProperty, callback: (Result<Unit>) -> Unit)
  fun isPaired(peripheralId: String, callback: (Result<Boolean>) -> Unit)
  fun pair(peripheralId: String, callback: (Result<Unit>) -> Unit)
  fun unPair(peripheralId: String, callback: (Result<Unit>) -> Unit)
  fun getSystemDevices(callback: (Result<List<UniversalBleScanResult>>) -> Unit)
  fun getConnectionState(peripheralId: String, callback: (Result<BleConnectionState>) -> Unit)
  fun readRssi(peripheralId: String, callback: (Result<Long>) -> Unit)
  fun requestConnectionPriority(peripheralId: String, priority: BleConnectionPriority, callback: (Result<Unit>) -> Unit)
  fun setLogLevel(level: BleLogLevel, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by UniversalBlePlatformChannel. */
    val codec: MessageCodec<Any?> by lazy {
      PrinterConnectPigeonCodec()
    }
    /** Sets up an instance of `UniversalBlePlatformChannel` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: UniversalBlePlatformChannel?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.getBluetoothAvailabilityState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getBluetoothAvailabilityState{ result: Result<AvailabilityState> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrinterConnectPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.hasPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.hasPermissions{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrinterConnectPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.requestPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestPermissions{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrinterConnectPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.enableBluetooth$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.enableBluetooth{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                reply.reply(PrinterConnectPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.disableBluetooth$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.disableBluetooth{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                reply.reply(PrinterConnectPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.startScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filtersArg = args[0] as List<UniversalScanFilter>
            val androidOptionsArg = args[1] as AndroidOptions
            api.startScan(filtersArg, androidOptionsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                reply.reply(PrinterConnectPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.stopScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopScan{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                reply.reply(PrinterConnectPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.isScanning$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isScanning{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrinterConnectPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val peripheralIdArg = args[0] as String
            val configArg = args[1] as ConnectionPlatformConfig
            api.connect(peripheralIdArg, configArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                reply.reply(PrinterConnectPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val peripheralIdArg = args[0] as String
            api.disconnect(peripheralIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                reply.reply(PrinterConnectPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.setNotifiable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val peripheralIdArg = args[0] as String
            val serviceIdArg = args[1] as String
            val characteristicIdArg = args[2] as String
            val valueArg = args[3] as BleInputProperty
            api.setNotifiable(peripheralIdArg, serviceIdArg, characteristicIdArg, valueArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                reply.reply(PrinterConnectPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.discoverServices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val peripheralIdArg = args[0] as String
            api.discoverServices(peripheralIdArg) { result: Result<List<UniversalBleService>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrinterConnectPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.readValue$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val peripheralIdArg = args[0] as String
            val serviceIdArg = args[1] as String
            val characteristicIdArg = args[2] as String
            api.readValue(peripheralIdArg, serviceIdArg, characteristicIdArg) { result: Result<UniversalBleCharacteristic> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrinterConnectPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.requestMtu$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val peripheralIdArg = args[0] as String
            val mtuArg = args[1] as Long
            api.requestMtu(peripheralIdArg, mtuArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrinterConnectPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.writeValue$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val peripheralIdArg = args[0] as String
            val serviceIdArg = args[1] as String
            val characteristicIdArg = args[2] as String
            val valueArg = args[3] as List<Long>
            val bleOutputPropertyArg = args[4] as BleOutputProperty
            api.writeValue(peripheralIdArg, serviceIdArg, characteristicIdArg, valueArg, bleOutputPropertyArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                reply.reply(PrinterConnectPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.isPaired$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val peripheralIdArg = args[0] as String
            api.isPaired(peripheralIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrinterConnectPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.pair$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val peripheralIdArg = args[0] as String
            api.pair(peripheralIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                reply.reply(PrinterConnectPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.unPair$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val peripheralIdArg = args[0] as String
            api.unPair(peripheralIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                reply.reply(PrinterConnectPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.getSystemDevices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getSystemDevices{ result: Result<List<UniversalBleScanResult>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrinterConnectPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.getConnectionState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val peripheralIdArg = args[0] as String
            api.getConnectionState(peripheralIdArg) { result: Result<BleConnectionState> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrinterConnectPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.readRssi$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val peripheralIdArg = args[0] as String
            api.readRssi(peripheralIdArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrinterConnectPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.requestConnectionPriority$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val peripheralIdArg = args[0] as String
            val priorityArg = args[1] as BleConnectionPriority
            api.requestConnectionPriority(peripheralIdArg, priorityArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                reply.reply(PrinterConnectPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.printer_connect.UniversalBlePlatformChannel.setLogLevel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val levelArg = args[0] as BleLogLevel
            api.setLogLevel(levelArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrinterConnectPigeonUtils.wrapError(error))
              } else {
                reply.reply(PrinterConnectPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class UniversalBleCallbackChannel(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by UniversalBleCallbackChannel. */
    val codec: MessageCodec<Any?> by lazy {
      PrinterConnectPigeonCodec()
    }
  }
  fun onAvailabilityChanged(stateArg: AvailabilityState, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onAvailabilityChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PrinterConnectPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onPairStateChange(peripheralIdArg: String, isPairedArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onPairStateChange$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(peripheralIdArg, isPairedArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PrinterConnectPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onScanResult(resultArg: UniversalBleScanResult, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onScanResult$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(resultArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PrinterConnectPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onValueChanged(peripheralIdArg: String, serviceIdArg: String, characteristicIdArg: String, valueArg: List<Long>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onValueChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(peripheralIdArg, serviceIdArg, characteristicIdArg, valueArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PrinterConnectPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onConnectionChanged(peripheralIdArg: String, stateArg: BleConnectionState, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onConnectionChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(peripheralIdArg, stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PrinterConnectPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onConnectionParametersUpdated(resultArg: BleConnectionParametersUpdated, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.printer_connect.UniversalBleCallbackChannel.onConnectionParametersUpdated$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(resultArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PrinterConnectPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
